<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IMC_Nickname</name>
   <tag></tag>
   <elementGuidId>1d1db5c8-2cc1-49ed-a364-813b1fb08538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/input[@name='CreateAccount-CreateAccountScreen-CreateAccountDV-Nickname']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
