<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IMC_Desc_Of_Operation</name>
   <tag></tag>
   <elementGuidId>2d28ac10-5f95-4d5f-8d6d-0847ed381909</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/textarea[@name='SubmissionWizard-LOBWizardStepGroup-SubmissionWizard_PolicyInfoScreen-SubmissionWizard_PolicyInfoDV-AccountInfoInputSet-CommercialInputSet-DescriptionOfOperation']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
