<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Contacts_TextBox_WorkPhone</name>
   <tag></tag>
   <elementGuidId>27deaa30-e061-439b-adc5-e584d51df083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
