<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Contacts_Link_Edit</name>
   <tag></tag>
   <elementGuidId>421b63a8-12e9-42df-a4fa-ca812d937a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccountFile_Contacts-AccountFile_ContactsScreen-AccountContactsLV-0-EditButton']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.gw-icon.gw-svg-icon.gw-svg-icon-edit.gw-font-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb42a8cd-60be-472f-98ae-f9b879efeeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-icon gw-svg-icon gw-svg-icon-edit gw-font-icon</value>
      <webElementGuid>f888ebdc-93cd-486a-9f55-ed8f1a31dfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-tooltip</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>981a8682-dd39-4512-8abf-38a55524ed90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8cc44c8-0faa-465a-ba71-fd5b13fd2ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>6ed495e4-3987-40cd-bf9b-1466c1ac5d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseenter</name>
      <type>Main</type>
      <value>gwMouse.enter</value>
      <webElementGuid>1379263e-aee3-4c12-ab84-b6808cf063d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mousemove</name>
      <type>Main</type>
      <value>gwTooltips.move</value>
      <webElementGuid>81219bff-e0c5-4e6d-865e-84a4472a3ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseout</name>
      <type>Main</type>
      <value>gwTooltips.hide</value>
      <webElementGuid>cadd935b-fa7f-4a86-b7ac-d0757d5638bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseover-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50ac4366-23a5-4a97-a95f-7afb640c9a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseout-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8302470-b1ec-49f9-aeec-01ceb375cd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mousemove-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6469669-558f-4448-9b77-f7e5c95db3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseenter-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6b1b13f-ee88-4ffb-b73c-bcf037641e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountFile_Contacts-AccountFile_ContactsScreen-AccountContactsLV-0-EditButton&quot;)/span[@class=&quot;gw-icon gw-svg-icon gw-svg-icon-edit gw-font-icon&quot;]</value>
      <webElementGuid>a3995f90-f13d-4439-a2ea-eade8fb35205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountFile_Contacts-AccountFile_ContactsScreen-AccountContactsLV-0-EditButton']/span</value>
      <webElementGuid>6b271fc6-ff18-4b93-9e87-abaf481697f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/span</value>
      <webElementGuid>231ab7f3-43b6-48ae-92a1-e21805474cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
