<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_ClassCodeSearch_TextBox_ClassCode</name>
   <tag></tag>
   <elementGuidId>f7b6d5a8-7ca0-4fc4-aa9d-19cf4650cf00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'ClassCodeSearchDV-Code')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;GL7ExposureClassCodePopup-GLClassCodeSearchScreen-GLClassCodeSearchDV-Code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb265a5c-8ac0-4fe5-80e9-98c759be9373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc675df1-85c9-4b4a-ae9a-254e7a6b9765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GL7ExposureClassCodePopup-GLClassCodeSearchScreen-GLClassCodeSearchDV-Code</value>
      <webElementGuid>e1458e26-38a6-4cbe-b67f-fd0b18087fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack gw-focus</value>
      <webElementGuid>ee9bd584-b2d0-47a8-8ea6-3b1b0fe7db1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1c36e78-df36-4939-ab42-49ea732896e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8dc78763-b529-446f-9acb-c91917967e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>44943c18-c75f-4ca1-ade6-044847cf0316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GL7ExposureClassCodePopup-GLClassCodeSearchScreen-GLClassCodeSearchDV-Code&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>706e6a81-79fc-48d1-8c64-24bfc7ecfb73</webElementGuid>
   </webElementProperties>
</WebElementEntity>
