<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Common_Button_Today</name>
   <tag></tag>
   <elementGuidId>dad48c9b-aadb-4416-8a78-f44129611ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-datePicker']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-datePicker--today.gw-button-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e237feb8-614b-469e-8017-d924ae9410bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-datePicker--today gw-button-secondary</value>
      <webElementGuid>042e5528-e3ef-47fd-b9a1-959675e81f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9885d5d5-c4d3-4ded-8745-7521570c052c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>gwDatePicker.today</value>
      <webElementGuid>117663e0-2504-4ff5-bcaf-69276b609136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>ddad7057-6149-414c-9c72-ed83bfce621a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-datePicker&quot;)/div[@class=&quot;gw-datePicker--footer gw-inDatePicker&quot;]/div[@class=&quot;gw-datePicker--today gw-button-secondary&quot;]</value>
      <webElementGuid>3ca5fdb2-3f65-4c92-bc59-738682d5e575</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-datePicker']/div[2]/div</value>
      <webElementGuid>febb0400-f5e0-499f-8d8d-af09b73a9ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[86]</value>
      <webElementGuid>6cbd77f6-075e-41ac-9034-08b11d9029a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::div[87]</value>
      <webElementGuid>4ce20249-7547-4241-a1d5-ae0b08a9cf25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Day'])[1]/preceding::div[2]</value>
      <webElementGuid>0640eca3-970b-4396-817e-020c1365021f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('IM 7051 Builders', &quot;'&quot;, ' Risk Coverage - Scheduled Jobsite - Limited')])[1]/preceding::div[25]</value>
      <webElementGuid>e70bf4e4-816f-4be5-956b-58541b746b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>81f9a06d-c20e-42f5-bc27-1c202a01b0a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>2e29eb13-7638-4386-8ebc-b5408222d791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>0ab67ad2-c3d6-4d47-a7db-3b1aec3c52aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
