<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Common_Label_LOB</name>
   <tag></tag>
   <elementGuidId>1ef4dad7-34eb-48a5-b773-abea44d66c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-JobWizardInfoBar-LOBLabel']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-JobWizardInfoBar-LOBLabel > div.gw-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1fa35e1-a97e-4cab-a9da-a9b0b4cf09eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>96c65e29-e60b-402c-88ac-52498ca3f534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commercial Package</value>
      <webElementGuid>eb09b4ed-2fb6-4fa5-b8c1-e9c1c293ebc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-JobWizardInfoBar-LOBLabel&quot;)/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>0e6fc06a-a8d9-4b82-9b9b-91ead5815ca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-JobWizardInfoBar-LOBLabel']/div</value>
      <webElementGuid>1a8a2e7a-8e9e-4f99-b85a-0d157f898761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission (Draft)'])[1]/following::div[3]</value>
      <webElementGuid>ae617eb5-0f9f-4c1a-a739-90ca5564ec6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::div[22]</value>
      <webElementGuid>783af5cb-9e4f-4b51-95ff-f5a60ff87aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective: 02/28/2023'])[1]/preceding::div[1]</value>
      <webElementGuid>840ae0ea-c3cf-4a5f-a3e5-e484bb49bde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary:'])[1]/preceding::div[3]</value>
      <webElementGuid>9176cc3f-76f7-4446-b422-655af8c6cfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Commercial Package']/parent::*</value>
      <webElementGuid>a575610c-5bdc-4a72-98d2-722329bcc0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>4bd0ac1e-882d-496a-8a7d-3b3f71568371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Commercial Package' or . = 'Commercial Package')]</value>
      <webElementGuid>f3cb39f0-84bc-4be4-9f87-c68e9d7698d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
