<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_NewSubmissions_Button_LOB_Select_WC</name>
   <tag></tag>
   <elementGuidId>5df916df-03df-4546-91c1-3fe97ffd5323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'Name')]//div[contains(text(),'Workers')]/../../../../..//div[text()='Select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3b45c1a-40f3-4e33-a02e-76b9b410b4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      <webElementGuid>09e362c5-6834-47a1-a0e2-e4d3a6504dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>a858f708-0c46-4d3f-b28d-90de7e1804e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>59815adc-4adc-4fa5-bbfe-ff312ec813a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>3f0c54fe-67d3-41d1-873a-858c563c2cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c42b33fa-eb6f-4f52-84fe-508ff4b6bd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>e5c7d3c3-40cb-43c2-8cf0-56a60830f585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission&quot;)</value>
      <webElementGuid>988ac34a-572a-4e86-9f83-ed9e11ab4427</webElementGuid>
   </webElementProperties>
</WebElementEntity>
