<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Payments_RadioButton_DBFullPay</name>
   <tag></tag>
   <elementGuidId>a3351cc0-db79-4caa-8c25-325b1114327b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio')] | //div[@id='SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9e0382e-479c-49e4-9a2c-1fabf8df0a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6cc5bac6-8000-4d7b-8e03-220a624ac40f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio</value>
      <webElementGuid>7741fd7a-59ed-47d6-a9cc-d7ead80801a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>43ac9d66-53a4-4280-92bd-62db767e4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-radio-group</name>
      <type>Main</type>
      <value>InstallmentsPlansGroup_Radio</value>
      <webElementGuid>7348ce7a-ad8f-4343-8275-8a569a133e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>412229a5-8038-4b36-b160-14db41e64832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-radio-button gw-focus gw-checked</value>
      <webElementGuid>f7e44fc1-1fa8-42bd-98bf-f112c19f6b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>gwRadioButtonGroup.radioButtonSelect</value>
      <webElementGuid>dd8e8ff4-7222-46c3-8184-20e00d4f9430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cd934eff-1008-4e8f-beb0-2b80d03e1339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>362c3338-ecb2-4084-a679-945a8936de41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio&quot;)</value>
      <webElementGuid>5064ae0e-8caf-4f69-af39-07236cbcae47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio']</value>
      <webElementGuid>e8680b21-2536-441c-831e-6e17ded40ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan']/div/div</value>
      <webElementGuid>c9102f9a-99f1-4bba-b125-8c2cfe6c1ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[3]/td/div/div/div/div</value>
      <webElementGuid>71e3e6b8-dbff-4c3f-80ea-f2a24a1bd2b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SubmissionWizard-SubmissionWizard_PaymentScreen-BillingAdjustmentsPanelSet-PaymentSchedulePanel-PlanInputSet-PaymentsPlanDV-PaymentsPlanInputSet-InstallmentPlan-BillingAdjustmentsInstallmentsLV-1-InstallmentPlan_radio']</value>
      <webElementGuid>7f1bd4fc-4b88-4ac2-bf02-570b7bcffebe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
