<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_StartCancellation_Dropdown_Source</name>
   <tag></tag>
   <elementGuidId>649e28a8-13b6-45c2-ae90-c83b37f699f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name='StartCancellation-StartCancellationScreen-CancelPolicyDV-Source']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
