<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_WC_StateCoverages_DropDown_ScheduleModificationTypeOverride - Copy</name>
   <tag></tag>
   <elementGuidId>e64b1e82-8c9f-43af-bb26-29a0e26aff59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Schedule Modification Type – Override']/..//select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b88e0af4-c6cc-4c97-9277-efaa5bed4ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType</value>
      <webElementGuid>d123f466-d0c8-4c20-aa5f-d306c67f22de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d0930244-2e9a-4cb2-9e31-daa650ca9b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>2418515a-17cd-40ad-96cd-655ec43f6b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>CreditDebit   </value>
      <webElementGuid>1b5aecb7-9ea9-40e7-8f66-d23579864a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>7bb88ce5-0575-4fd2-9e4c-343e7a14527f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType']</value>
      <webElementGuid>9e31bf15-cbe6-4eec-89a5-ab97a8052274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType']/div/div/select</value>
      <webElementGuid>7578076d-d5f2-4177-a740-3c429f19233c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Modification Type – Override'])[1]/following::select[1]</value>
      <webElementGuid>efce15e8-cf2c-4fcb-b5b4-79605d749cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Modification (%) – Override'])[1]/following::select[2]</value>
      <webElementGuid>3d25e446-8456-4b47-877b-1e342bced8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comment'])[1]/preceding::select[1]</value>
      <webElementGuid>e93441b8-0557-4e15-8e29-713d8cb1bc45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Covered Employees'])[1]/preceding::select[1]</value>
      <webElementGuid>a7a58beb-8f56-4eb0-995f-8d644e8189cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div/select</value>
      <webElementGuid>a0177d73-3064-4120-b3f5-d779818e1fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'RenewalWizard-LOBWizardStepGroup-LineWizardStepSet-WC7StateCoverageScreen-WC7StateCoverageCV-WC7PolicyLinePerStateConfigDV-UnsplitModifiers-WC7ModifiersInputSet-WC7JurisdictionModifierInput-WC7JurisdictionModifierInputSet-ModIterator-0-HMICScheduleModInputGroup-CPAScheduleModOverrideType' and (text() = '   &lt;none>CreditDebit   ' or . = '   &lt;none>CreditDebit   ')]</value>
      <webElementGuid>2f2af31c-2260-4c85-8064-3858aa913c7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
