<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AcctInfo_TypeList_1stAddress</name>
   <tag></tag>
   <elementGuidId>54a8dc2b-906c-4b36-9f90-20da51f3223d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>93b49415-1b7a-4957-bf11-cdc930dc8b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cbdf1bda-91d0-437d-a5db-f83b802e82e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a01b7a8a-3bc7-4cff-aaa3-8124f65e786b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR</value>
      <webElementGuid>77faacb5-d3c3-4e6f-aace-502d274b4b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100 Main Street, Auburn, Indiana, USA</value>
      <webElementGuid>02b9c29d-1979-4316-a18c-4d17b964df81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR&quot;]</value>
      <webElementGuid>f7a67087-59f1-4b4f-9e11-7b342b1cd7b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_typeaheadDropdownList']/li[2]</value>
      <webElementGuid>37cb6d8f-2db6-42d0-b7be-38157b7c9559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::li[2]</value>
      <webElementGuid>8194a1dd-9c04-440a-8ec7-6145a7ea4a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[3]/following::li[2]</value>
      <webElementGuid>35fbd7de-2534-456f-9c49-10ed4fc325f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 2'])[1]/preceding::li[4]</value>
      <webElementGuid>969b63e8-a247-4010-b2b3-3b9e7480bde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address 3'])[1]/preceding::li[4]</value>
      <webElementGuid>3f2afdfa-f8ec-4bd2-8894-f32a62346d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100 Main Street, Auburn, Indiana, USA']/parent::*</value>
      <webElementGuid>bf2dd250-9ac2-4663-85a9-24971f85e633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>2f2d3a3f-7136-433d-a6b8-18ede6b38f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '100 Main Street, Auburn, Indiana, USA' or . = '100 Main Street, Auburn, Indiana, USA')]</value>
      <webElementGuid>27f7bca5-f61b-4e72-ab58-34961af21726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
