<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_input_OccupancyAndInterest</name>
   <tag></tag>
   <elementGuidId>9a6d4daf-cb8b-45d4-a9f2-fb97c3950f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='occupancyAndInterest']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#occupancyAndInterest</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b68570a6-b56f-4687-be3b-08a3add40d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>occupancyAndInterest</value>
      <webElementGuid>15c99b59-b4ac-44aa-8a0f-7aaa482d8a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c7e6a3c-3c3d-4fe7-9a16-4f1d813cef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>52e0a3f2-2ae6-409b-bf99-74e344adcb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>dbcbfae3-db84-4ac5-bec4-b1a3563530a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc9a817c-aa5e-4e0e-94af-fbd5a45678b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>occupancyAndInterest_1440013438</value>
      <webElementGuid>b79afc5d-d0f9-45e1-b96c-9d472b8f399f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>a03b77ad-156e-49fa-ab23-dcb0a9bea9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Owner, lessee, etc..</value>
      <webElementGuid>eed4d591-f9cb-416e-a9c3-982dfa761cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;occupancyAndInterest&quot;)</value>
      <webElementGuid>32b15218-112e-4931-aee2-4a6e960ae132</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='occupancyAndInterest']</value>
      <webElementGuid>45142aa3-ec34-467e-a007-a55a43925f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div/div/div/div/div/div[2]/div/div[2]/div/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>9b143164-972b-4056-a101-20aa3bf38af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>dbdda66a-abf5-4650-9276-9f320c37e790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'occupancyAndInterest' and @type = 'text' and @placeholder = 'Owner, lessee, etc..']</value>
      <webElementGuid>e8f36f2d-cf93-4ce9-abae-f75b8c91745a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
