<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_Select_Model_Autos</name>
   <tag></tag>
   <elementGuidId>06a78d87-cc2c-497f-a036-e145784e9b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='CAMARO 2SS']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-23-option-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7764e685-970d-40b9-a01d-e8f19affe9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>70c2239e-5555-4fbe-8b90-19f949a76fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-23-option-4</value>
      <webElementGuid>3ec70c65-6bdf-4ce3-a9cb-25438987ab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>360abb8d-0b79-4d14-85e6-ff87f3274221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAMARO 2SS</value>
      <webElementGuid>33732d83-922b-484c-9588-02d15f7b2b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-23-option-4&quot;)</value>
      <webElementGuid>05475213-2af3-421c-8644-bb7d719c277e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-23-option-4']</value>
      <webElementGuid>0f00d4d6-9fd0-4968-81a2-bf21f35d4486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAMARO 2LT'])[1]/following::div[1]</value>
      <webElementGuid>469613af-36ed-4a5b-8f8e-bc7897deb8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOLT EV PREMIER'])[1]/following::div[2]</value>
      <webElementGuid>0bcaa6f4-308c-4571-be03-33a084a645d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAMARO LS'])[1]/preceding::div[1]</value>
      <webElementGuid>a755d1f8-99d4-4ba6-b20f-0d512f1058af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAMARO LT'])[1]/preceding::div[2]</value>
      <webElementGuid>7b807b9a-9fad-42f4-9886-5ec27c72d772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CAMARO 2SS']/parent::*</value>
      <webElementGuid>6479ae19-0b9b-44b6-a2c6-dc73b9ba34bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[5]</value>
      <webElementGuid>5c8cd555-d8cc-49df-adfc-d27ab87e573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-23-option-4' and (text() = 'CAMARO 2SS' or . = 'CAMARO 2SS')]</value>
      <webElementGuid>2a1c9a48-62b2-4874-a249-954f6b213d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
