<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_Watercraft_Select_Year_1954</name>
   <tag></tag>
   <elementGuidId>d4d93feb-0a07-421e-9f8a-4968ef403053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='1954']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-36-option-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d4ba948-2c28-471e-a083-61e3d760b181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicGenericSelectControl__option jut__GenericSelectControl__option jut__GenericSelectControl__optionFocused css-1n7v3ny-option</value>
      <webElementGuid>5f758532-8ba9-4a2d-8851-329d25e99831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-36-option-5</value>
      <webElementGuid>c4edd9d0-d9f1-4e45-a02c-9e69b767bf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7786013d-6238-448a-bc70-5ef4666cbc65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1954</value>
      <webElementGuid>b1b35bf4-13dd-4371-8f79-b540b701d620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-36-option-5&quot;)</value>
      <webElementGuid>fd0170ae-c06b-4346-b18f-f6b4c6115133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-36-option-5']</value>
      <webElementGuid>91112b26-013c-405a-a5cf-38d90e8b2f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[5]/following::div[5]</value>
      <webElementGuid>57f1fd92-0f46-4b64-9589-fce99ae3803f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'react-select-36-option-5', '&quot;', ')')])[1]/following::div[15]</value>
      <webElementGuid>dfa6554e-9e3b-4f35-bc91-59236ce99370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1954']/parent::*</value>
      <webElementGuid>0f982ec0-abce-4a92-b8aa-e295c6a18588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[6]</value>
      <webElementGuid>be083584-7fef-4a03-8ae3-233270eede0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-36-option-5' and (text() = '1954' or . = '1954')]</value>
      <webElementGuid>148359cf-a8a2-4e9b-ba42-449ea524d2ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
