<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IMC Account search button</name>
   <tag></tag>
   <elementGuidId>f25e83b0-e4a6-457f-836b-b71464099556</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TabBar-AccountTab-AccountTab_AccountNumberSearchItem_Button']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TabBar-AccountTab-AccountTab_AccountNumberSearchItem_Button > span.gw-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9f2dd15-c0de-433d-a1ca-a3bbf50643d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-icon</value>
      <webElementGuid>c858d77b-19e3-4cfe-b7b6-98eefbf77e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>520d111f-27ba-4fb7-913b-39d868b23536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>gw-search-icon</value>
      <webElementGuid>b807023f-8a42-4b81-a579-2e4ac1938a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar-AccountTab-AccountTab_AccountNumberSearchItem_Button&quot;)/span[@class=&quot;gw-icon&quot;]</value>
      <webElementGuid>b2a4e7d0-ff0c-462b-89de-043f737ecb5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TabBar-AccountTab-AccountTab_AccountNumberSearchItem_Button']/span</value>
      <webElementGuid>a8f0b77d-da0f-4ac5-a1c3-da6a61cc5172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>40253d7c-9fb9-41f8-a0b7-09a5b6187fa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
