<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Coverages_Excluded_Delaware2</name>
   <tag></tag>
   <elementGuidId>edb23ffc-a58b-48c7-8214-43a15b98bb54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-35-option-7']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-35-option-7 > div.jut__LookupField__item > div.jut__LookupField__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01db59ed-d0cf-49f6-8fd8-38059135eecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__LookupField__title</value>
      <webElementGuid>90d04076-243b-46a0-893b-3ac84f23e53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delaware</value>
      <webElementGuid>e9da4e56-4b76-4423-8d49-5058d1b7054a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-35-option-7&quot;)/div[@class=&quot;jut__LookupField__item&quot;]/div[@class=&quot;jut__LookupField__title&quot;]</value>
      <webElementGuid>3ec590fc-0441-499f-8258-61b0080656dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-35-option-7']/div/div</value>
      <webElementGuid>ab990a1d-20ce-4497-8d8d-729f9b89638a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[7]/following::div[3]</value>
      <webElementGuid>55b00f95-ce87-4d72-b83a-c482c053725b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connecticut'])[1]/following::div[4]</value>
      <webElementGuid>afe0259c-8aae-42eb-a6cd-ccd97469d9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[8]/preceding::div[1]</value>
      <webElementGuid>c2e5f009-2292-46a5-b3d1-0feb6cf728d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District of Columbia'])[1]/preceding::div[2]</value>
      <webElementGuid>24879c17-2dbd-4522-af4e-0a478afa1996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delaware']/parent::*</value>
      <webElementGuid>d7ef8894-c3aa-417b-9ddc-0ed9c19a3490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>67629497-29a1-40a5-8da2-0592c2a07e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Delaware' or . = 'Delaware')]</value>
      <webElementGuid>bfbd79da-6a0c-47ec-b89a-c0f93e11006d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
