<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_c_gw-icon gw-icon--expand (1)</name>
   <tag></tag>
   <elementGuidId>14f41b3d-88e2-4ffe-8e2b-f962e0d9c3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='TabBar-AccountTab']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TabBar-AccountTab > div.gw-action--expand-button > div.gw-icon.gw-icon--expand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3b42077-372c-41db-b0c0-c10e0547a4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-icon gw-icon--expand</value>
      <webElementGuid>8040a764-0a82-4739-a7c5-3478682a8726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar-AccountTab&quot;)/div[@class=&quot;gw-action--expand-button&quot;]/div[@class=&quot;gw-icon gw-icon--expand&quot;]</value>
      <webElementGuid>24ff0552-be83-440d-adce-8fb2a2f13f44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TabBar-AccountTab']/div[3]/div</value>
      <webElementGuid>57997c2d-3a1b-4041-909f-f5604d4d16ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[3]/div</value>
      <webElementGuid>7eef30a1-b144-4c26-a104-49abcbe7bbcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
