<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Actions</name>
   <tag></tag>
   <elementGuidId>41190e7d-ccae-4c32-b4b9-8797d2e8b04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AccountFile-AccountFileMenuActions']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a975e275-1e59-40e1-b947-cd93982a5825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d533c3c-512e-401a-a488-43209d41eff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-focus</value>
      <webElementGuid>5415ce6e-ee35-4786-b07b-345317d194bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c52ce1a-44f1-453d-931c-4055694a6b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e6504bf-5af1-447e-a410-9ec26059520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7419c835-1cc4-4ac6-a13a-c021afc987fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>toggleSubMenu</value>
      <webElementGuid>5d89abf0-4c46-4b2f-a824-8d1ae9b58ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>22d80979-e27f-4d7e-b1d0-aa46a91846a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actions</value>
      <webElementGuid>fc8d62b4-6814-4b25-b7d6-8839630910fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountFile-AccountFileMenuActions&quot;)/div[@class=&quot;gw-action--inner gw-focus&quot;]</value>
      <webElementGuid>e7ad237a-0679-4a40-b9ee-38aab72e5be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AccountFile-AccountFileMenuActions']/div</value>
      <webElementGuid>04b55982-1fd1-45ce-ac7e-78e8e4d89946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out Test UWSupervisor'])[1]/following::div[8]</value>
      <webElementGuid>6c8cfdd5-201e-4e6b-a665-34ec9ad2b6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LO'])[1]/following::div[9]</value>
      <webElementGuid>4f99faed-3035-4a04-b373-5edf5c64774f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>30f875e7-ca40-4de5-9229-52d43ea49d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Actions' or . = 'Actions')]</value>
      <webElementGuid>c509be92-bb3a-433e-90b8-115555742233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
