<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PePerson</name>
   <tag></tag>
   <elementGuidId>9d2765ee-e5d7-4467-a432-f6383d076e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewAccount-NewAccountScreen-NewAccountButton-NewAccount_Person']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>551e4f4a-e83e-41b9-9b65-b59c9a87a35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>461a86ea-8eb0-4ba8-b084-6210f54d98dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-hasDivider gw-focus</value>
      <webElementGuid>32813d99-80ad-47ec-a808-bd34778d3dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>530ed505-61d0-4317-a4da-c18eb2f889af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5c7a8bc6-fcfd-4556-88ed-6d58b632dbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:^</value>
      <webElementGuid>09ee59f6-31c0-41bb-8610-0619420c5901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dcb3d291-3a1b-49b1-8b72-fb5cd1838f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PePerson</value>
      <webElementGuid>c56e3f68-b9ad-4bc1-9b33-d0bb0534241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAccount-NewAccountScreen-NewAccountButton-NewAccount_Person&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]</value>
      <webElementGuid>b43360fb-3c20-4eb2-b9a1-30253f2c478c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewAccount-NewAccountScreen-NewAccountButton-NewAccount_Person']/div</value>
      <webElementGuid>cb6fb3a2-9cca-4f88-b1b2-d54d7498e8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::div[2]</value>
      <webElementGuid>be631b5d-5aa9-41df-9541-fc359c8715c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Co'])[3]/following::div[3]</value>
      <webElementGuid>c0dfbca4-94dc-4463-8460-c036e6950d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>a8f321d3-fdb9-4e8e-a5f6-80a2b8c30d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PePerson' or . = 'PePerson')]</value>
      <webElementGuid>9cdce108-b985-422a-93ec-ee4d8547bfaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
