<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select_1</name>
   <tag></tag>
   <elementGuidId>d55c8329-1c1f-4676-a766-596e249a0522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[td[contains(@id, 'Name_Cell')]//div[text()='Commercial Inland Marine']]//td[contains(@id, 'Select')]//div[text()='Select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-addSubmission</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d047dbf8-2e6f-444f-af9f-3d0dca62d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-addSubmission</value>
      <webElementGuid>c37234dd-e92b-4a52-b839-dcae9d5da9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>53d4cfd2-0e36-4776-9525-3999225c0027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>b386b341-1d2c-4313-b6f4-c4870a158fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>dbe8e381-023d-44b3-aa9b-a27edc2a2444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa54ea9a-28a8-44e0-9c43-f7c93a8237f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>abb23fc9-5d95-4a11-b808-65a637e0998f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-addSubmission&quot;)</value>
      <webElementGuid>952314d3-11c7-430a-ade9-7be01666827e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-addSubmission']</value>
      <webElementGuid>a7712e5d-ac2d-49db-ba51-e923f8cdd5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-Select']/div/div/div</value>
      <webElementGuid>f7caa10d-e71e-4682-a612-c7d73b7af6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::div[8]</value>
      <webElementGuid>8dbca77d-6f40-4fb1-ae5b-0c6001ff1c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[15]</value>
      <webElementGuid>4ed6c502-6169-43a9-9e32-3614ff59907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Inland Marine'])[1]/preceding::div[1]</value>
      <webElementGuid>9b668f39-277d-481c-a649-27191b6a720c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Inland Marine'])[2]/preceding::div[5]</value>
      <webElementGuid>730c5bf2-77de-4f2e-b07c-e9821b62f9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>0086d00a-9741-4982-8245-1e5268adffdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td/div/div/div</value>
      <webElementGuid>7879c3e3-7960-4cb3-a85b-c0826aecf187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-0-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>69354f25-c915-4357-8ad8-9a46fa091bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
