<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Phone_EditAccountContactPopup-Co_4c1fe1</name>
   <tag></tag>
   <elementGuidId>245e79e7-792e-45dd-b486-3baf4ab74594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5579eeb1-a01d-45c3-9c8e-bddde09c4060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adbd61ab-c8dd-4fdd-b9c3-2d5246057438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber</value>
      <webElementGuid>7bcda64a-873f-4c1b-ab2b-7491b8e1826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cd87f42-9106-4c7f-aa7b-e721ba9e57b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>255f33b1-c064-4fc7-87c9-56420e6a7110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>4da2b005-bc50-4624-81c9-4932d39b5bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>86b54a66-6d61-4afd-9af1-de232a621781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>9f21e292-2052-440b-b28e-7b988e68353a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber']</value>
      <webElementGuid>1d83c8d0-e366-44fc-894c-c570fee5fdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber']/div/input</value>
      <webElementGuid>f01c2ad8-8aab-43e1-9415-096b343cca5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div/div/input</value>
      <webElementGuid>1a8b892e-1a7b-4c4d-af6b-47b889a3bad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'EditAccountContactPopup-ContactDetailScreen-AccountContactCV-AccountContactDV-ContactNameInputSet-WorkPhone-GlobalPhoneInputSet-NationalSubscriberNumber']</value>
      <webElementGuid>14a68a92-4570-4c20-b2db-f9fdea9129a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
