<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Quote_Header_Quote</name>
   <tag></tag>
   <elementGuidId>7882e79a-5e91-44f8-8f0a-5feba634bc7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.WizardPanel_header__2j4mJ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>fb35a24d-0c47-42d6-bff7-055f2d92e3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WizardPanel_header__2j4mJ</value>
      <webElementGuid>efb4356a-90e4-4701-a628-d9fc5d68e077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Step 6: Quote</value>
      <webElementGuid>1109d06e-0a87-4e0b-b81e-eca8edf59456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_headerWrapper__3znBf&quot;]/h4[@class=&quot;WizardPanel_header__2j4mJ&quot;]</value>
      <webElementGuid>bb946268-14de-4bed-882c-c5181e4c59a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div/h4</value>
      <webElementGuid>55c53c2f-67f6-4159-93a4-987172c59850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bcunningham@hastingsmutual.com'])[1]/following::h4[1]</value>
      <webElementGuid>51cdf563-bcc1-4813-9e62-f318edc6fe36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brandy Cunningham'])[1]/following::h4[1]</value>
      <webElementGuid>ade1e87f-d557-4b9b-8972-44e3343f1b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a New Version'])[1]/preceding::h4[1]</value>
      <webElementGuid>eebcdf4c-96d3-4d42-9252-9aa06c98e74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Annual Premium:'])[1]/preceding::h4[1]</value>
      <webElementGuid>5108f86a-7dab-40e8-aa8f-663a49d776aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h4</value>
      <webElementGuid>2ca2dbe7-61bc-4158-affb-351da9c12cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Step 6: Quote' or . = 'Step 6: Quote')]</value>
      <webElementGuid>9fdb776a-a61d-456a-9b6e-845af801e388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
