<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Loc_TextBox_TotalPayroll</name>
   <tag></tag>
   <elementGuidId>e147ffbd-d479-46a3-89cd-65f7cb853bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalPayroll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalPayroll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6226e1b8-8922-4a62-a8bd-80de551339ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalPayroll</value>
      <webElementGuid>c9e30cb0-0a84-4b2c-820e-308dda9c0592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c20d05f3-b8fb-4516-b57b-853d79711622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>fce1879d-9197-4876-906a-c800749e72a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>207a5b79-8211-40d7-8c80-fdf34b144fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>191a984f-bb2b-437f-b7a8-a97ae037cadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>totalPayroll_1440013438</value>
      <webElementGuid>a8c1f823-7713-49cb-a006-076210306355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>$1,000</value>
      <webElementGuid>a68d17f5-b082-4ccf-882c-81b4a2745d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>$1,000</value>
      <webElementGuid>463f7409-2481-45fa-be99-44ba7134f709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>61e64a25-7a90-43f4-8a26-4b13fdb95a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalPayroll&quot;)</value>
      <webElementGuid>45fd0d5f-c2b1-42d7-8b8e-79f6ca39c076</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalPayroll']</value>
      <webElementGuid>501178f2-89ea-4225-8d11-c772ed2f5674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/div/div[3]/div[4]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>6393be8e-04f6-422e-bc3e-8e2ddb96f00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>1a0cfdeb-7728-41a0-9bd0-ffa243d6c7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'totalPayroll' and @type = 'text' and @placeholder = '$1,000']</value>
      <webElementGuid>751a422b-bd1d-4ee3-a490-00e9876d516c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
