<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_Radiobtn_UMUIM_Accept_Autos</name>
   <tag></tag>
   <elementGuidId>401e8571-249a-48ab-bdb7-ecf073edcb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.jut__RadioButton__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Autos'])[1]/following::label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b70064d0-37f3-42d6-bd8a-9c8107588a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>includeUmUim_Accept</value>
      <webElementGuid>78ea6263-c28a-48e0-bc5b-ec89ff6a9901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>03df535b-2da5-43f1-8916-e9cac6a825d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__label</value>
      <webElementGuid>82447a0b-6b34-4306-88de-fa243a4b577a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>3f39aa82-9477-4523-8304-6b091729f089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;includeUmUim&quot;)/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]</value>
      <webElementGuid>6616d3e7-e87d-4202-9d2e-31464fc9a103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='includeUmUim']/div/label</value>
      <webElementGuid>65fa0379-0264-4ad0-a001-ee9deeb8f90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include UM / UIM Coverage?'])[1]/following::label[1]</value>
      <webElementGuid>480e6dbf-b519-49d2-a654-ded2fc5ef430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Autos'])[1]/following::label[2]</value>
      <webElementGuid>317f8527-3062-4838-88e6-9c640db6148a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/preceding::label[1]</value>
      <webElementGuid>3db1713f-fa7f-4456-bace-48cbb25d3045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label</value>
      <webElementGuid>6614e918-5896-4767-9e7b-acc53fdc9156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>4dcae677-2a10-4887-bb9c-4bdd799107f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
