<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AdditionalInfo_input_CertHolder_ZipCode</name>
   <tag></tag>
   <elementGuidId>f711af62-3c61-4546-b131-8b1f5acb278e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-kbguqo3qkzd-address-yqzkzr0hmr8-zip']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
