<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_PolDetails_TextBox_SSN</name>
   <tag></tag>
   <elementGuidId>1b87a241-e3b8-4833-b3b9-cefaee830ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-5hdipbmxzwo-ssnId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,&quot;ssn&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>458b3500-bb3e-4da2-a4ff-185fcaf2cb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-5hdipbmxzwo-ssnId</value>
      <webElementGuid>f6cc7394-2ef4-4562-8b41-ece84b689908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>788f52fc-d758-4e92-980e-4308c2608a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask jut__InputMaskField__empty invalid</value>
      <webElementGuid>7555c217-78e0-49ec-a522-9a188731a03a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc12a7e0-4366-424b-b9cf-e2240107c33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eec11d36-c1b3-4c96-ad63-2067e43e84d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-5hdipbmxzwo-ssnId_1440013438</value>
      <webElementGuid>ba108f8b-bfd2-4054-9e02-c3161e47537b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>5fb7454f-ce36-444d-b352-d0c07e41893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>eecd8d31-114c-4bd8-a947-8aac56d874f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>43311a27-21f4-412a-ad8e-812c3a3e257f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>___-__-____</value>
      <webElementGuid>9500b67a-0463-4876-b3d7-c2684b9cd529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-5hdipbmxzwo-ssnId&quot;)</value>
      <webElementGuid>224484c5-9608-4e00-8088-7d6032c3bb57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-5hdipbmxzwo-ssnId']</value>
      <webElementGuid>59f83661-ada4-426e-88f0-745b1acde7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div[2]/div/div/div[5]/div/div/div[2]/input</value>
      <webElementGuid>cf73981a-3d33-4ac2-882f-833c453ba8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/input</value>
      <webElementGuid>ad917bc6-26d3-4d79-b4d0-d863b7eb46db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-5hdipbmxzwo-ssnId' and @type = 'text' and @placeholder = '#########']</value>
      <webElementGuid>7c2f45ce-ea8f-4d9a-aa2b-967c035c30cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
