<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AccInfo_TextBox_Address (1)</name>
   <tag></tag>
   <elementGuidId>7e942dcc-4060-46c5-bac5-86eba86deccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'addressTypeAhead_contact')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c933d219-3b7a-4fb2-abe6-447157803a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI</value>
      <webElementGuid>cfc93fde-5953-4069-85a0-c989d2abfe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55393df2-cf8c-41f4-a789-3c188665d17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>d488cba9-2b81-428d-8b29-a3960a1df0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-jp0dhqd1yn-address-7b9nflk4845 address-line1</value>
      <webElementGuid>f99885f5-854b-467a-9613-a50bd7efee43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdaf1504-6450-408c-b418-3514b5b36479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI_1440013438</value>
      <webElementGuid>2b8f0e8f-b14b-4814-9c00-c6afdbf091f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>9f84e1d6-4e97-401d-8935-cd7621111a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>1c1a77b5-5c3a-4e22-a1f4-00ef1477f4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI&quot;)</value>
      <webElementGuid>db893819-8db1-4ba2-a7f0-57842d91be7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI']</value>
      <webElementGuid>41c861fc-390b-40e7-b5cb-9ba8097519fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/div[3]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>dcef2198-2fb0-45b6-8cd7-6435d8ef6b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f8754414-9298-4c3c-8cee-50726389f4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-jp0dhqd1yn-address-7b9nflk4845-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>a26fbfce-650b-4909-aa6c-f74f6e5352bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
