<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Exposures_CheckBox_Autos</name>
   <tag></tag>
   <elementGuidId>b619ec8f-3b12-41ca-bfce-cd23df127502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.Autos_autoForm__2myVs > div.FieldSet_container__3odpU > div.jut__FieldComponent__fieldComponent.smallOverline > div.jut__FieldComponent__contentContainer.jut__FieldComponent__controls > div.jut__CheckboxField__checkbox > span.jut__CheckboxField__checkboxElement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1669a0be-a2ce-4dcc-9db7-e988c43b1ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__CheckboxField__checkboxElement</value>
      <webElementGuid>690c2048-3211-4f67-b130-fc25dd6433fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Autos</value>
      <webElementGuid>7956fe79-315b-4e8f-aee5-82731c91041a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e7c09cf-d480-402f-b357-2ffe733f4b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d2bb6d2c-cbcb-459c-a241-4072c0037a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8fa64c3f-d070-4565-9aad-d7e0c06546da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;PageContainer_standard__3bPCs&quot;]/div[@class=&quot;QuoteWizard_container__3EESf&quot;]/div[1]/div[@class=&quot;Wizard_bottomContainer__3lWO5&quot;]/div[2]/div[1]/div[@class=&quot;WizardPanel_body__21TLo&quot;]/div[@class=&quot;Exposures_form__3Ll82&quot;]/div[@class=&quot;Exposures_form__3Ll82&quot;]/div[2]/div[@class=&quot;Autos_autoForm__2myVs&quot;]/div[@class=&quot;FieldSet_container__3odpU&quot;]/div[@class=&quot;jut__FieldComponent__fieldComponent smallOverline&quot;]/div[@class=&quot;jut__FieldComponent__contentContainer jut__FieldComponent__controls&quot;]/div[@class=&quot;jut__CheckboxField__checkbox&quot;]/span[@class=&quot;jut__CheckboxField__checkboxElement&quot;]</value>
      <webElementGuid>707f0a1d-e348-4b27-bb86-7fb84929eff0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div/div/span</value>
      <webElementGuid>f6cb7e83-cec0-49d2-ac37-68c2dca59bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span</value>
      <webElementGuid>a4919e85-a1fd-4cf9-8bc9-e2e76256c2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
