<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Loc_TextBox_MaxNumOfEmp</name>
   <tag></tag>
   <elementGuidId>c59e0316-f57d-42ee-899b-ecee0ac6b8a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employeeCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employeeCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a57e8c36-6d6d-45d1-8f60-03293e81bb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employeeCount</value>
      <webElementGuid>708685e7-1f6f-4c01-9614-1ee740e6a526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bf7c991-da72-438d-944c-e9b2521fe87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input invalid</value>
      <webElementGuid>646c4130-49de-4056-a2df-e99c11262f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>afe9701b-0282-47ec-bf99-89de6e2f4ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8707e6ff-1d8b-4728-a225-1918d3c69deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>employeeCount_1440013438</value>
      <webElementGuid>87366ee0-0f29-44de-827d-d680f0d2e154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4212fed6-e85e-4a20-8c5c-306ce043fad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>ee0c43d5-06fa-48b2-a90f-fc009fbf9f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>0d7e359e-58f7-4da5-aa97-34845c50604a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employeeCount&quot;)</value>
      <webElementGuid>598bcf18-48cd-4db6-9c8d-d0de60e31916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employeeCount']</value>
      <webElementGuid>dcb73c23-e76f-4b97-883e-9b87ae958f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[3]/div/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>f094cd92-f025-462f-b088-5d78f821baa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>2f5c63e7-c59d-4da2-88c6-d8d9b09cc65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'employeeCount' and @type = 'text' and @placeholder = '10']</value>
      <webElementGuid>fb68e4e3-28cb-4c96-be58-1f0fa2b37c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
