<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_AccInfo_Address_Iowa</name>
   <tag></tag>
   <elementGuidId>09396401-22e3-437b-af05-c763585c365b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='addressTypeAhead_contact-ubbl0chu4k-address-inm7jxcmsyh-googleAddressAPI_typeaheadDropdownList']/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR.AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>74bb69f6-696b-438b-bcd8-bba4b862aa2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6b4e95cb-0078-4cf7-be55-aa0bc55a4987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1a68db7-4079-4f80-8bd5-2ae4a31d67be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df</value>
      <webElementGuid>52792f0e-e972-4e3f-a854-c6d7b53da859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Iowa Avenue, Iowa City, IA, USA</value>
      <webElementGuid>1ce01c3a-ad37-4bbb-941b-fecedc615db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-ubbl0chu4k-address-inm7jxcmsyh-googleAddressAPI_typeaheadDropdownList&quot;)/li[@class=&quot;AddressLookupTypeaheadComponent_gw-typeahead__match__BO7BR AddressLookupTypeaheadComponent_gw-typeahead__match_active__3f9Df&quot;]</value>
      <webElementGuid>685992e6-d546-4e55-82d7-34c30e1d7c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='addressTypeAhead_contact-ubbl0chu4k-address-inm7jxcmsyh-googleAddressAPI_typeaheadDropdownList']/li[3]</value>
      <webElementGuid>9bc7ad51-3518-4a45-9de1-c2781bc3a2af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iowa Street, Alma, MI, USA'])[1]/following::li[1]</value>
      <webElementGuid>34e45d22-80f3-4762-9066-155f384556d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iowa Street Southwest, Wyoming, MI, USA'])[1]/following::li[2]</value>
      <webElementGuid>8f3b1402-ab35-458d-88ea-62deb18e3cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iowa St, Midland, MI, USA'])[1]/preceding::li[1]</value>
      <webElementGuid>636c0f53-4ecd-4f7f-b198-af9b1c57a575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iowa St, Melrose Park, IL, USA'])[1]/preceding::li[2]</value>
      <webElementGuid>96f7b081-dcc7-403c-9723-2ceab3cd1484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Iowa Avenue, Iowa City, IA, USA']/parent::*</value>
      <webElementGuid>ea91195d-85e3-4b55-b954-c5a701da917f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>7a5ae1e0-35b1-4fb9-a98a-d6dca733ea64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Iowa Avenue, Iowa City, IA, USA' or . = 'Iowa Avenue, Iowa City, IA, USA')]</value>
      <webElementGuid>1ce037f8-5008-46d0-adae-653010c5c3cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
