<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Payments_PaymentPlans_AgencyPayCardSelection</name>
   <tag></tag>
   <elementGuidId>221bac93-b3c7-4c48-826a-ef2eecd34bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mir.mi-chevron-right.dynamicIcon__xlarge.Icon_xlarge__8JRem.colorAccent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gridbc:579001']/div[3]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>927ea025-f592-4158-b075-d95a0da6d440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mir mi-chevron-right dynamicIcon__xlarge Icon_xlarge__8JRem colorAccent</value>
      <webElementGuid>65b1b051-b1a5-4724-8f6a-3b0f7ce746a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridbc:579001&quot;)/div[3]/i[@class=&quot;mir mi-chevron-right dynamicIcon__xlarge Icon_xlarge__8JRem colorAccent&quot;]</value>
      <webElementGuid>2962e214-0967-4c98-9cbe-4321f50bf6aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridbc:579001']/div[3]/i</value>
      <webElementGuid>fc76dce1-ba6e-471b-97c0-2d34081c28e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>fee141c5-3fa0-4e51-8389-76ae87117274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
