<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Payments_Auto_PaymentMethod_Savedpayments_Add Payment Method_Selection</name>
   <tag></tag>
   <elementGuidId>45b82378-dc08-497e-8f56-a44860d2b767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mir.mi-chevron-right.dynamicIcon__xlarge.Icon_xlarge__8JRem.colorAccent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b27cdb1e-0c09-4b5c-940e-97a335c399d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mir mi-chevron-right dynamicIcon__xlarge Icon_xlarge__8JRem colorAccent</value>
      <webElementGuid>025697cd-d48e-4dee-9566-541317468147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethodCard&quot;)/section[@id=&quot;paymentDetails&quot;]/div[2]/div[@class=&quot;QuotePaymentComponent_main__sp19U&quot;]/div[@id=&quot;paymentSources&quot;]/div[@class=&quot;PaymentInstrumentButton_container__1Kb3D&quot;]/div[@class=&quot;PaymentInstrumentButton_fullWidth__1B5RR&quot;]/div[@id=&quot;pibc:639009&quot;]/div[@id=&quot;gridbc:639009&quot;]/div[3]/i[@class=&quot;mir mi-chevron-right dynamicIcon__xlarge Icon_xlarge__8JRem colorAccent&quot;]</value>
      <webElementGuid>8ed14efc-f8c3-4617-a3c1-f1d182749d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gridbc:639009']/div[3]/i</value>
      <webElementGuid>2d0498ac-bf68-488e-a103-62519b2020c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/i</value>
      <webElementGuid>334ab306-36dd-441e-8393-5974e015d08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
