<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_Payments_PaymentPlans_Monthly</name>
   <tag></tag>
   <elementGuidId>262bee8b-7990-45ea-b9fb-c1dd5399c484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='billingAndPaymentsCard']/div/div[4]/table/tbody/tr[5]/td/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0649f029-507a-444d-bdf4-e49d49925f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__RadioButton__text jut__RadioButton__primaryText</value>
      <webElementGuid>320e294e-8de3-4283-9407-176800e2af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly</value>
      <webElementGuid>8e29dd4f-d235-46bf-b6b9-176a6cf3eee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAndPaymentsCard&quot;)/div[1]/div[@class=&quot;dynamicTable__table jut__Table__table jut__Table__hoverable hmic__Table__default hmic__Table__alternatingRowColorsFlipped PaymentStep_dataTable__2o3PO&quot;]/table[@class=&quot;jut__Table__tableElement&quot;]/tbody[1]/tr[@class=&quot;jut__Table__row&quot;]/td[@class=&quot;dynamicTable__tableCell jut__Table__tableCell text-left&quot;]/div[@class=&quot;dynamicRadioButton__radioButton jut__RadioButton__radioButton jut__Table__radio&quot;]/label[@class=&quot;jut__RadioButton__label&quot;]/span[@class=&quot;jut__RadioButton__text jut__RadioButton__primaryText&quot;]</value>
      <webElementGuid>96f84044-6d5b-4c39-9df4-4a83dc4f4c5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='billingAndPaymentsCard']/div/div[4]/table/tbody/tr[5]/td/div/label/span</value>
      <webElementGuid>bd2dff90-b38e-4e8f-8c08-9039f5815cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$320.00'])[6]/following::span[1]</value>
      <webElementGuid>7e2a7539-568a-49ed-8a24-4727591f425d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$80.00'])[2]/following::span[2]</value>
      <webElementGuid>68bb3364-de43-40b2-8821-1b512d523553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$53.34'])[1]/preceding::span[1]</value>
      <webElementGuid>93ab6c2c-ff1f-4bac-8098-b9e58cd725f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$26.67'])[2]/preceding::span[2]</value>
      <webElementGuid>209a505c-6d3e-497b-937e-ab43e78b71e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monthly']/parent::*</value>
      <webElementGuid>df683710-ec10-47f6-987f-ca9f0efba0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div/label/span</value>
      <webElementGuid>a32f9e04-4e00-4638-8886-fc89b26e6fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Monthly' or . = 'Monthly')]</value>
      <webElementGuid>ebd9e518-beeb-483b-ba51-f6dfe33898bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
