<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_USERNAME_UserName</name>
   <tag></tag>
   <elementGuidId>a1b69c0f-fc40-498b-bbb5-5e2cbdb957ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UserName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UserName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f33eb4a-aa1a-4475-908a-06c9b709cfb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control border border-2 hmicTextInputHeight</value>
      <webElementGuid>6fc31d41-005b-4310-b51f-2a97c6f52836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>13e3beef-79a2-480b-8df6-89b545e63876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UserName</value>
      <webElementGuid>79b94058-6951-49b5-b921-34f92c7dfbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d1e702a-e14a-4cd6-9253-895e852c5028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UserName&quot;)</value>
      <webElementGuid>b93d5db6-563b-44cf-90ec-84909206109d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UserName']</value>
      <webElementGuid>d1329233-02ec-4432-8315-e9266af7b207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>8136f343-2d1b-4e03-a088-78ef4b831f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>da8528be-613d-4811-94ad-2c9fa6092c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UserName' and @name = 'UserName' and @type = 'text']</value>
      <webElementGuid>f7988cde-0817-497d-a6b6-be5c52a26866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
