<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_addressTypeAhead_contact-h0t3_37bc04</name>
   <tag></tag>
   <elementGuidId>5aefbbe3-f5d3-4dc2-b832-1e2a7cf5a7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6397a6a1-71e8-41b4-ab88-12a7aabcc8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI</value>
      <webElementGuid>d17d135f-4b02-4d54-bd93-ef19218af40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d41e5ea0-1e41-498d-9c85-2147cb47c4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>836cedcc-6cff-4528-8459-7705b2d2d23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>section-contact-h0t3a8nl54t-address-vjmpktr27ad address-line1</value>
      <webElementGuid>c535ee9b-b597-4775-8d4e-8dd6e1943859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>366d1b2b-8213-4f0b-9258-e4fc0d3dad13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI_1440013438</value>
      <webElementGuid>63d33f59-4832-4570-8cf4-1cd19ef2638c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>8d0a1cbe-0e41-4d49-b27e-30a87be19bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address</value>
      <webElementGuid>4d79bf92-43dd-4170-a4a7-a6d312b89522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI&quot;)</value>
      <webElementGuid>2f7bf9b8-ec2b-4027-bfc7-a9e711fe584a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI']</value>
      <webElementGuid>1204b206-8fd1-480b-b924-326327be3ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>8108fdda-e0eb-4aeb-be8f-9d4e52cab3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a8cca68d-b32d-4b5b-bf49-c282c8eea3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'addressTypeAhead_contact-h0t3a8nl54t-address-vjmpktr27ad-googleAddressAPI' and @type = 'text' and @placeholder = 'Street address']</value>
      <webElementGuid>d248a98e-b4af-498e-955d-0862a82d4bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
