<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submission (Draft)Commercial Inland Mar_c0a10e</name>
   <tag></tag>
   <elementGuidId>bc6be4e0-bd12-4edb-b59e-2cb5998b4a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-JobWizardInfoBar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-JobWizardInfoBar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>350c0465-c188-4e7c-a142-7c3ed41b4bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-JobWizardInfoBar</value>
      <webElementGuid>b8a2e1aa-52d6-450c-a960-5eef5b9844b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-InfoBarWidget gw-styleTag--CenterPanelWidget</value>
      <webElementGuid>88b76c6c-ab0f-4e43-abb0-732c86d2d76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>068efd10-b539-4a3f-88f9-397757fa3acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>info bar</value>
      <webElementGuid>dc79e347-3fa7-439a-967e-5d89d9093855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submission (Draft)Commercial Inland MarineEffective: 09/10/2024Primary:test coverageAccount:AC02622473Underwriter:Super User</value>
      <webElementGuid>9230c97c-dbc1-4fc0-9e4f-6cf8e687cc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-JobWizardInfoBar&quot;)</value>
      <webElementGuid>1a67c25d-f668-4c53-910c-a859cdc1d248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-JobWizardInfoBar']</value>
      <webElementGuid>71863725-6ef1-4f45-9bb8-4f0c111084af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-center-top-section']/div[2]</value>
      <webElementGuid>c3b8a54d-b9e8-4106-8149-6b4f28c05ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::div[17]</value>
      <webElementGuid>7bf926cd-7f5b-4288-9092-80146a12e6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi'])[1]/following::div[18]</value>
      <webElementGuid>e4aaee2a-32cb-46f2-97fc-c04850f71b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]</value>
      <webElementGuid>1304bdbd-d750-4faa-a9ae-57d0796370ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SubmissionWizard-JobWizardInfoBar' and (text() = 'Submission (Draft)Commercial Inland MarineEffective: 09/10/2024Primary:test coverageAccount:AC02622473Underwriter:Super User' or . = 'Submission (Draft)Commercial Inland MarineEffective: 09/10/2024Primary:test coverageAccount:AC02622473Underwriter:Super User')]</value>
      <webElementGuid>3cce723a-1929-447b-a200-7cf26220ffaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
