<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_31</name>
   <tag></tag>
   <elementGuidId>e87118f6-ac0c-440c-8cce-cad116146551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-datePicker']/table/tbody/tr[5]/td[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-datePicker--day-label.gw-datePicker--today-cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0230fab6-2cad-4cce-b1c9-b27c88818fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-datePicker--day-label gw-datePicker--today-cell</value>
      <webElementGuid>e910e448-ecb5-473f-98b2-e7d1428ec586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>938c4b5a-1ec2-4a4b-865a-00c5bdbd1d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-datePicker&quot;)/table[@class=&quot;gw-datePicker--calendar gw-inDatePicker&quot;]/tbody[1]/tr[5]/td[@class=&quot;gw-datePicker--keyEventDay gw-datePicker--today-cell&quot;]/div[@class=&quot;gw-datePicker--day-label gw-datePicker--today-cell&quot;]</value>
      <webElementGuid>40c9c236-49eb-4aa2-986d-789fd0c8a39b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-datePicker']/table/tbody/tr[5]/td[5]/div</value>
      <webElementGuid>e3f3169c-4f20-4bb9-a364-5cc2186f733d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/following::div[65]</value>
      <webElementGuid>711dee2b-f8f4-45f2-9bd0-340ffce6d6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::div[66]</value>
      <webElementGuid>8a87ca12-3408-4b05-9bb7-77f4dee362ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/preceding::div[20]</value>
      <webElementGuid>fe5d33c1-6920-4e36-8f33-741128c91d2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Day'])[1]/preceding::div[22]</value>
      <webElementGuid>986fc041-2c66-4b01-9818-16148e53acec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>e1149aa9-c229-48fa-92fc-c3ef3a49c310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[5]/div</value>
      <webElementGuid>c61d75ff-e16d-43e9-9d0c-533ff273a18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '31' or . = '31')]</value>
      <webElementGuid>52101edc-0a8f-4e56-a3f9-87a27a58bcb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
