<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coverage Name_SubmissionWizard-LOBWiz_4cb8f9</name>
   <tag></tag>
   <elementGuidId>3b77cf36-1915-49b0-8d54-1f9c8ef74380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3544a0b5-6cda-4d65-beb4-d018478d8e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4aca7d9f-811a-4b35-bcde-2322e3465afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>004b1403-79e3-44cd-a572-8ab084e46007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox</value>
      <webElementGuid>228e0464-9c4c-4543-93b8-d090efaa0657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-7</value>
      <webElementGuid>a306718b-ebbd-4ca2-a084-e691e4993c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>-,coverableParts</value>
      <webElementGuid>0ab242f0-4a56-4220-9204-3fb32acb85ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>81926b70-7f9c-4a14-ad97-6d8401d9ec15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>bf7c404f-1cad-497d-b585-6233082331c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox']</value>
      <webElementGuid>9d6f8bbc-c641-499f-bc7b-452ce0dca7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox']/input</value>
      <webElementGuid>174f3ec3-1ed2-4d0a-82cc-cd86bea2bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/input</value>
      <webElementGuid>93d30212-be56-4a97-8880-543486213ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-IM7InlandMarineScreen-IM7InlandMarinePanelSet-0-_Checkbox']</value>
      <webElementGuid>43f42ace-1b07-4fd6-9073-3a4917649145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
