<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Description_NewActivityWorksheet-NewA_36498c</name>
   <tag></tag>
   <elementGuidId>6c0c5435-c000-4e62-ab28-d28ac0aa8649</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80582e8f-34a1-452e-8071-263d6db920b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2d5ad86-b409-4b53-bb81-faf7b32c11fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description</value>
      <webElementGuid>b94514fb-44a3-43cb-9285-c7e6be68e857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7aa73c7d-ffee-431e-9278-a82254302364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1333</value>
      <webElementGuid>887fdddb-5139-42df-8a3d-30736d951196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b84966b0-96fd-4ee1-a25f-b5743d1f1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>181c4509-0eb1-4562-bcbe-4a582c2773ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>bb849fbc-82fe-4fc6-b391-7f6e32e3497b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>05ce16a8-b936-47ee-aaef-9123acc5747c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description']</value>
      <webElementGuid>2707a634-ba63-4590-a77f-595c6e62b289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description']/div/input</value>
      <webElementGuid>0bfb2a4b-e10d-4710-a9fb-a7c1a07b2130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>57f8691d-a265-4ac5-ad0e-95daa3f7d265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NewActivityWorksheet-NewActivityScreen-NewActivityDV-Description']</value>
      <webElementGuid>4be2154e-30cf-423d-af22-b8475ccbfad7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
