<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Losses_SubmissionWizard-Job_Ris_3bb92b</name>
   <tag></tag>
   <elementGuidId>4a6c336b-608a-4076-be3d-fa207342e89d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5eb191e1-d059-4012-94f6-f1b3b424f0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a20e0bc9-a195-4b8d-a73e-0434f8e33998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier</value>
      <webElementGuid>518ccde4-da81-441d-99f3-0210cb3543b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2921bb2-0a1e-491b-adc8-238771075063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>d346f6d6-cb0a-4145-82a0-86735154dd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>336afcbe-5db9-471c-bd90-ad85f9818585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>90e283e8-0562-4d00-bcb9-1c85514476b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>d3d7a7fc-0896-4008-8616-f7d94470a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>49d295a9-13d2-4400-b8ea-ff8053ee094a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier']</value>
      <webElementGuid>b88ab1e3-700b-447a-8a03-7ef750e57cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier']/div/input</value>
      <webElementGuid>7c10a7d7-bd93-42d8-ba9c-2af580461f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/input</value>
      <webElementGuid>0355d647-11f4-408b-9af0-e438cfe31719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-PriorHistoryDV-PriorPolicyLV-0-Carrier']</value>
      <webElementGuid>a5a8c4b5-dcc5-4347-bde1-7e9735289780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
