<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_LineCov_WI Waiver_input_No. of Contracts_termValue</name>
   <tag></tag>
   <elementGuidId>3292f2c2-bd8e-4cbd-9e18-ca52d2d7c703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termValue--sxu6pex5p9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div/div[3]/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>890be398-f551-4d46-8a14-009d248a8233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termValue--sxu6pex5p9</value>
      <webElementGuid>73f3b32e-8909-421f-a412-10a7f20aef24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a750e6c-47db-4f5a-8bf2-907a26a7fc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dynamicInput__input jut__InputField__input</value>
      <webElementGuid>aea7d086-a3dd-4fa6-91ec-0dc5f45139cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f2fb818b-de68-43d7-949b-a2d10d6eefa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8866aee-0f9f-4d97-bd8d-23776d70d7e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>termValue--sxu6pex5p9_1440013438</value>
      <webElementGuid>4bbb254e-eb5a-4971-a008-bdf973b80dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termValue--sxu6pex5p9&quot;)</value>
      <webElementGuid>882b989f-930e-41e4-aea3-93830ce9016b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termValue--sxu6pex5p9']</value>
      <webElementGuid>e45883e8-3a16-444f-b017-ccd4f5786c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/div/div[3]/div/div[2]/div/div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>dd6fd56a-7d67-4159-9228-f73d712d6165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>4d366e0a-d084-44b3-b4c4-bf83cfbe1dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termValue--sxu6pex5p9' and @type = 'text']</value>
      <webElementGuid>8b4efd6f-3680-409d-bc76-a87566967ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
