<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Portal_PolicyDetails_SSNTextField</name>
   <tag></tag>
   <elementGuidId>76fc0df2-dd81-40e3-a937-0d32ea1f1ab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact-zlsbpzvmyb-ssnId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact-zlsbpzvmyb-ssnId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cda6331b-5f22-4de0-be29-2d8055e4b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact-zlsbpzvmyb-ssnId</value>
      <webElementGuid>540428b6-479d-4430-b1ce-8361f536c63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d261f3fa-ee7c-4dc3-aaef-f068b8dfd089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jut__InputField__input dynamicInputMask__inputMask jut__InputMaskField__inputMask</value>
      <webElementGuid>72dfed4d-43c8-48c4-8f2d-7be7287eff83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4434c5ea-3cbd-4142-88dc-9bec89cab88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc27a801-daf6-4bbe-add6-3ead00ad3e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>contact-zlsbpzvmyb-ssnId_1440013438</value>
      <webElementGuid>64da7507-92e8-4743-bc20-2e3eb16f8df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>553e207f-468d-4b18-9413-a879f638bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>db39ce51-5c4a-4bd5-8d61-378f13f72a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>#########</value>
      <webElementGuid>b5b91c54-be4d-40fe-9cb6-76f805a16d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>234-56-7890</value>
      <webElementGuid>1bc5ff34-9c5d-4a86-a40e-fa5eaa01a3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-zlsbpzvmyb-ssnId&quot;)</value>
      <webElementGuid>fb702f5a-ffc3-4c72-8ad2-c650f129225e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact-zlsbpzvmyb-ssnId']</value>
      <webElementGuid>db8ec2af-68f3-466b-83b2-55a815ee64a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div/div[2]/div[2]/div/div[2]/div/div/div[5]/div/div/div[2]/div/div/div[4]/div/div/div[2]/input</value>
      <webElementGuid>6f0fb6fa-4f61-4350-906b-b8be3a8cd49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5a854d08-c8ae-4c7e-8cbf-b61db60f5618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contact-zlsbpzvmyb-ssnId' and @type = 'text' and @placeholder = '#########']</value>
      <webElementGuid>2c57b762-1990-4035-9521-141b0c3484c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
