<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Audit_Participants_Select_AssignedGroup</name>
   <tag></tag>
   <elementGuidId>4622805a-3025-4328-b9d5-8ca4b2e04087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17192158-9671-4fcd-94a5-3071ed4addde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup</value>
      <webElementGuid>4ac8e779-6d9e-45aa-93f7-f3e57b95c5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccc45ebb-4a09-4909-ba03-0fe00cfe574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9b549b87-d300-42c0-9b99-2705d84e0adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Audit ProcessorsEntryMiscellaneous Production AuditingRatingReviewing   </value>
      <webElementGuid>aa479e8a-7dbd-451e-a899-a0511848b2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>6be27795-b538-4ecd-9668-d61fa93e2c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup']</value>
      <webElementGuid>7f8d4d97-2a6e-4584-a39e-ffcf3ef4e7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup']/div/div/select</value>
      <webElementGuid>1b9af72e-ac68-4818-9c42-0c0c67f1ec09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select User...'])[1]/following::select[1]</value>
      <webElementGuid>2a603d02-c666-4d0e-ad0b-2183eda6ed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renewal Com Proc'])[1]/following::select[2]</value>
      <webElementGuid>cd138362-4ef1-46b5-ac7a-3a0847a39438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div/div/select</value>
      <webElementGuid>2b493082-cfa1-4201-80d1-b486e076c299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedGroup' and (text() = '   &lt;none>Audit ProcessorsEntryMiscellaneous Production AuditingRatingReviewing   ' or . = '   &lt;none>Audit ProcessorsEntryMiscellaneous Production AuditingRatingReviewing   ')]</value>
      <webElementGuid>97c4ae58-b89d-4e4c-ba3d-dbc8c9eb13d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
