<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Audit_Participants_Click_btn_SelectUser</name>
   <tag></tag>
   <elementGuidId>f25b7304-8a48-4485-8e3c-ee537fdddb96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21cd36cb-7055-4e56-a3f1-52325cf9ca35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem</value>
      <webElementGuid>02e9c00a-0836-4b06-a587-98f775c073d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--ValueWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>e880e047-6646-44d9-9ac9-9442239607d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>d05153ee-e4ff-4fca-b93f-9dfda5fca698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>46d10b5d-5b31-4863-acf4-4e41d15304ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>599e9cde-7628-430f-8b87-954a53802b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select User...</value>
      <webElementGuid>21932348-b616-4de4-950e-fde9adef6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem&quot;)</value>
      <webElementGuid>9e047a50-20c3-45c0-9397-f27f3757ebae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem']</value>
      <webElementGuid>76a41bc6-75ab-4a38-b9ea-71e0b92a1441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser']/div[2]/div</value>
      <webElementGuid>b776ceff-03d3-4adb-8074-30e8bf1203c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renewal Com Proc'])[1]/following::div[15]</value>
      <webElementGuid>3650608e-9acd-4416-8055-eccf080ebcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Processor3'])[1]/following::div[22]</value>
      <webElementGuid>27137959-02f9-4248-9be7-db5f5cff7fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select User...']/parent::*</value>
      <webElementGuid>f705b6de-4c7b-46e4-855d-8df240e17268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/div[2]/div</value>
      <webElementGuid>21bd55dc-6b69-424c-b533-81eff8124626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'AuditWizard-JobWizardToolsMenuWizardStepSet-ParticipantsScreen-JobRolesLV-1-AssignedUser-UserBrowseMenuItem' and (text() = 'Select User...' or . = 'Select User...')]</value>
      <webElementGuid>abfeba97-0214-4638-86c2-0e20442e6bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
