<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_BuildersRisk_CheckBox_IM7050</name>
   <tag></tag>
   <elementGuidId>9b33c1c1-02a6-4dcf-a8a2-1f2cae727493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79589d8e-8da7-4452-aeb2-c8cac23e5d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>a433c06f-4525-4d6f-bca4-ad5118c0d60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5f4fe260-f47f-4ce1-8878-25b244ea7ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>IM 7050 Builders' Risk Coverage - Scheduled Jobsite Form - Comprehensive visibility toggle</value>
      <webElementGuid>3b304081-f4c2-47ec-9f76-69846b1bd133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>a24217c4-ac23-4e20-830e-24073060385c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>35873541-9dfc-480c-a26d-79680f3a6889</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>6b47c2d8-4684-4ef4-88b2-f9d596730da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>cb90b86b-4bbe-482f-afe2-c3fa59c5117a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>cd82af77-022c-4d6e-ac98-deca536ab457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>4c69db51-1c0b-4d99-b0e0-c797f428409a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
