<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_NewBuilding_Occupancy_DropDown_OccupancyCategory</name>
   <tag></tag>
   <elementGuidId>f13ba9cb-7b85-4244-b04c-75cbc63e5cfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>29a9b11f-8545-4b0d-850a-c8452a3dd31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input</value>
      <webElementGuid>a2be55ff-8ce2-498d-a589-048f96070855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8a0d3720-36d2-48f7-b5ff-86922f52955a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>81bf0efb-0b68-4ecc-9679-297b267cbeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Residential Apartments and CondominiumsOfficesMercantileMotels and HotelsInstitutionalIndustrial and ProcessingServiceContractors   </value>
      <webElementGuid>0185d8cf-1a8b-4f2e-8918-7b1c88792b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>249e8db5-077f-4475-a7d7-9119ca589910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>93c1cd8f-8d1d-4e72-8975-bdbbae6057c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input']/div/div/select</value>
      <webElementGuid>e14a9931-b94a-4822-9509-f9134847ca35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy Category'])[1]/following::select[1]</value>
      <webElementGuid>e98b402a-f883-42be-bb53-6360441e511d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sprinkler System'])[1]/following::select[2]</value>
      <webElementGuid>35abf9c8-a0bf-4e41-b68c-8fdc910f9cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Square Footage'])[1]/preceding::select[1]</value>
      <webElementGuid>e421a85e-fb41-4b53-85e2-e14169581035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverages'])[1]/preceding::select[1]</value>
      <webElementGuid>24fe7484-259a-4efd-b860-5b377c7c6318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div/select</value>
      <webElementGuid>b152965a-282b-459d-9733-a1534de1e50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CP7OccupancyClassPopup-CP7OccupancyCV-LobEntityDV-6-LobInputSet-LobInternalInputSet-Input' and (text() = '   &lt;none>Residential Apartments and CondominiumsOfficesMercantileMotels and HotelsInstitutionalIndustrial and ProcessingServiceContractors   ' or . = '   &lt;none>Residential Apartments and CondominiumsOfficesMercantileMotels and HotelsInstitutionalIndustrial and ProcessingServiceContractors   ')]</value>
      <webElementGuid>55dcab86-36b6-4f4b-bb6f-6a7712bb5312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
