<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_SpecialClass_DropDown_ClassDescription</name>
   <tag></tag>
   <elementGuidId>c3b309ea-aff5-4ae9-9435-ac31d325607b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4bcb0f4d-828f-4f99-91f4-1495f9bf8b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input</value>
      <webElementGuid>d982bd9e-d3fe-4087-be12-f60cc96bee31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>591678ed-a494-4c55-b026-ebed1a2a75e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>ee8a42a3-b886-4b99-aeda-459e825e0dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Aircraft Beacons, Blinkers and Other Lighting Equipment - Metal SupportsAircraft Beacons, Blinkers and Other Lighting Equipment - Wood SupportsAircraft Stored in the OpenAmusement Equipment in the Open (Commercial Enterprises) - Combustible EquipmentAmusement Equipment in the Open (Commercial Enterprises) - Metal or Other Non-combustible EquipmentArtificial TurfAwnings or Canopies (when Insured Separately) - Entirely Non-combustible, Including SupportsAwnings or Canopies (when Insured Separately) - Other than AboveBillboards and Signs (Not on Buildings) - Entirely Metal, Including Frame and SupportsBillboards and Signs (Not on Buildings) - Other than AboveBleachersBoats, Dredges or Vessels on Land or Permanently AnchoredBridges, Aqueducts - Concrete, Including Supports and DeckBridges, Aqueducts - Metal, Including Supports and DeckBridges, Aqueducts - Wood or Part WoodCooling Towers - MasonryCooling Towers - MetalCooling Towers - WoodCordwood, Felled Timber, Stakes &amp; RR Ties in Open, Not on Prem of a Lumber Mill or Bldrs Supply YardCranes and Other Heavy Machinery in the OpenDrive in Theaters (Speakers and Screens Only) - Screens - ConcreteDrive in Theaters (Speakers and Screens Only) - Screens - MetalDrive in Theaters (Speakers and Screens Only) - Screens - WoodDrive in Theaters (Speakers and Screens Only) - SpeakersElectric Transformers in the Open Not Owned by a Public Utility - on Concrete Pads or Steel SupportsElectric Transformers in the Open Not Owned by a Public Utility - on Wood SupportsElectric Vehicle Charging Stations (Pole Mount or Pedestal; Not Wall Mounted)Exhibit Stands and Booths in the Open - Entirely MetalExhibit Stands and Booths in the Open - Wood or Part WoodExplosives in the OpenFences and Arbors - Metal or MasonryFences and Arbors - WoodIncinerators or Refuse Burners Which Are Not Part of a Building - All Other ConstructionIncinerators or Refuse Burners Which Are Not Part of a Building - Masonry ConstructionMachinery and Equipmt in the Open - Procg Combustible Materials Other than Hay, Straw or FibersMachinery and Equipment in the Open - Processing Hay, Straw or Other FibersMachinery and Equipment in the Open - Processing Non-combustible Materials OnlyMotion Picture Sets in the OpenNursery Stock in the Open - Trees, Shrubs, Plants, FlowersOil DerricksOther - Masonry or Metal or Other Non-combustible Materials, Stock or EquipmentOther - Materials, Stock or Equipment Which Are Combustible or Part CombustibleOther - Metal or Other Non-combustible Materials W Combustible Wrappings, or on Combustible PalletsRafts and Other Floating Equipment, Also Portable or Movable Docks (Not Boats or Dredges)Reservoir RoofsSawmills, Portable, in the OpenSolar Panel Arrays - Freestanding (Not on Buildings), including strut supportStock Pens, Feed Pens, Feed Storing Pens, Corrals - Not Subject to Division Four - FarmStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - MetalStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - WoodSwimming Pools in the Open - Above Ground (All Other)Swimming Pools in the Open - Above Ground (Concrete or Metal)Swimming Pools in the Open - in Ground (All Other)Swimming Pools in the Open - in Ground (Concrete or Metal)Tanks, Bins &amp; Silos - Tanks Above Grnd - Masonry Tanks on the Grnd, Masonry Tanks W Masonry SupportsTanks, Bins &amp; Silos -Tanks Above Grnd -Steel Tanks on Grnd, Masonry or Steel Tanks on Steel SupportsTanks, Bins &amp; Silos - Tanks Above Grnd - Wood Tanks or Tanks W Wood Supports (Incldg Wood Rsv Roofs)Tanks, Bins and Silos - Tanks Below Ground, Covered with EarthTents and Fabric Covered Structures - Air Supported StructuresTents and Fabric Covered Structures - All Other Fabric Covered StructuresTents and Fabric Covered Structures - Supported by Structural Metal MembersTowers - Broadcasting Antennas (Cell, Radio and TV)Towers - Receiving Antennas (Cell, Radio and TV)Towers - Smokestacks or Chimneys (Free Standing) - MasonryTowers - Smokestacks or Chimneys (Free Standing) - MetalTunnels &amp; Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine) - Masonry or MetalTunnels and Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine Passageways) - WoodWater or Sewage Lift Pumps (Enclosed or Open) - Metal or MasonryWater or Sewage Lift Pumps (Enclosed or Open) - Wood or Part WoodWind Towers - Windmills and wind turbines - tower base of concrete, reinf masonry, steel constrctnWind Towers - Windmills and wind turbines - other   </value>
      <webElementGuid>53b8df9a-7946-4871-9949-3dbe2ebf7b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>efb7e663-53fc-417e-811d-e5bccbe9df09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>6f9ad3d4-8f09-415c-aa08-0b13a9044cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input']/div/div/select</value>
      <webElementGuid>0424afad-1dd3-4969-a606-756798ce9f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Description'])[1]/following::select[1]</value>
      <webElementGuid>1923012d-2f95-4c8c-abf8-45236bf7b6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Form'])[1]/following::select[2]</value>
      <webElementGuid>22f7369c-5c98-4284-9f8c-fefe6d5e6aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Code'])[1]/preceding::select[1]</value>
      <webElementGuid>bc3ff961-4fe6-4632-9879-8031c2a67d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this Special Class associated with a Building'])[1]/preceding::select[2]</value>
      <webElementGuid>531014a7-cf74-4560-a20a-28164b12baac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>bc48edc1-1649-4324-b57c-756abfeefd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CP7SpecialClassPopup-CP7SpecialClassCV-LobEntityDV-2-LobInputSet-LobInternalInputSet-Input' and (text() = '   &lt;none>Aircraft Beacons, Blinkers and Other Lighting Equipment - Metal SupportsAircraft Beacons, Blinkers and Other Lighting Equipment - Wood SupportsAircraft Stored in the OpenAmusement Equipment in the Open (Commercial Enterprises) - Combustible EquipmentAmusement Equipment in the Open (Commercial Enterprises) - Metal or Other Non-combustible EquipmentArtificial TurfAwnings or Canopies (when Insured Separately) - Entirely Non-combustible, Including SupportsAwnings or Canopies (when Insured Separately) - Other than AboveBillboards and Signs (Not on Buildings) - Entirely Metal, Including Frame and SupportsBillboards and Signs (Not on Buildings) - Other than AboveBleachersBoats, Dredges or Vessels on Land or Permanently AnchoredBridges, Aqueducts - Concrete, Including Supports and DeckBridges, Aqueducts - Metal, Including Supports and DeckBridges, Aqueducts - Wood or Part WoodCooling Towers - MasonryCooling Towers - MetalCooling Towers - WoodCordwood, Felled Timber, Stakes &amp; RR Ties in Open, Not on Prem of a Lumber Mill or Bldrs Supply YardCranes and Other Heavy Machinery in the OpenDrive in Theaters (Speakers and Screens Only) - Screens - ConcreteDrive in Theaters (Speakers and Screens Only) - Screens - MetalDrive in Theaters (Speakers and Screens Only) - Screens - WoodDrive in Theaters (Speakers and Screens Only) - SpeakersElectric Transformers in the Open Not Owned by a Public Utility - on Concrete Pads or Steel SupportsElectric Transformers in the Open Not Owned by a Public Utility - on Wood SupportsElectric Vehicle Charging Stations (Pole Mount or Pedestal; Not Wall Mounted)Exhibit Stands and Booths in the Open - Entirely MetalExhibit Stands and Booths in the Open - Wood or Part WoodExplosives in the OpenFences and Arbors - Metal or MasonryFences and Arbors - WoodIncinerators or Refuse Burners Which Are Not Part of a Building - All Other ConstructionIncinerators or Refuse Burners Which Are Not Part of a Building - Masonry ConstructionMachinery and Equipmt in the Open - Procg Combustible Materials Other than Hay, Straw or FibersMachinery and Equipment in the Open - Processing Hay, Straw or Other FibersMachinery and Equipment in the Open - Processing Non-combustible Materials OnlyMotion Picture Sets in the OpenNursery Stock in the Open - Trees, Shrubs, Plants, FlowersOil DerricksOther - Masonry or Metal or Other Non-combustible Materials, Stock or EquipmentOther - Materials, Stock or Equipment Which Are Combustible or Part CombustibleOther - Metal or Other Non-combustible Materials W Combustible Wrappings, or on Combustible PalletsRafts and Other Floating Equipment, Also Portable or Movable Docks (Not Boats or Dredges)Reservoir RoofsSawmills, Portable, in the OpenSolar Panel Arrays - Freestanding (Not on Buildings), including strut supportStock Pens, Feed Pens, Feed Storing Pens, Corrals - Not Subject to Division Four - FarmStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - MetalStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - WoodSwimming Pools in the Open - Above Ground (All Other)Swimming Pools in the Open - Above Ground (Concrete or Metal)Swimming Pools in the Open - in Ground (All Other)Swimming Pools in the Open - in Ground (Concrete or Metal)Tanks, Bins &amp; Silos - Tanks Above Grnd - Masonry Tanks on the Grnd, Masonry Tanks W Masonry SupportsTanks, Bins &amp; Silos -Tanks Above Grnd -Steel Tanks on Grnd, Masonry or Steel Tanks on Steel SupportsTanks, Bins &amp; Silos - Tanks Above Grnd - Wood Tanks or Tanks W Wood Supports (Incldg Wood Rsv Roofs)Tanks, Bins and Silos - Tanks Below Ground, Covered with EarthTents and Fabric Covered Structures - Air Supported StructuresTents and Fabric Covered Structures - All Other Fabric Covered StructuresTents and Fabric Covered Structures - Supported by Structural Metal MembersTowers - Broadcasting Antennas (Cell, Radio and TV)Towers - Receiving Antennas (Cell, Radio and TV)Towers - Smokestacks or Chimneys (Free Standing) - MasonryTowers - Smokestacks or Chimneys (Free Standing) - MetalTunnels &amp; Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine) - Masonry or MetalTunnels and Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine Passageways) - WoodWater or Sewage Lift Pumps (Enclosed or Open) - Metal or MasonryWater or Sewage Lift Pumps (Enclosed or Open) - Wood or Part WoodWind Towers - Windmills and wind turbines - tower base of concrete, reinf masonry, steel constrctnWind Towers - Windmills and wind turbines - other   ' or . = '   &lt;none>Aircraft Beacons, Blinkers and Other Lighting Equipment - Metal SupportsAircraft Beacons, Blinkers and Other Lighting Equipment - Wood SupportsAircraft Stored in the OpenAmusement Equipment in the Open (Commercial Enterprises) - Combustible EquipmentAmusement Equipment in the Open (Commercial Enterprises) - Metal or Other Non-combustible EquipmentArtificial TurfAwnings or Canopies (when Insured Separately) - Entirely Non-combustible, Including SupportsAwnings or Canopies (when Insured Separately) - Other than AboveBillboards and Signs (Not on Buildings) - Entirely Metal, Including Frame and SupportsBillboards and Signs (Not on Buildings) - Other than AboveBleachersBoats, Dredges or Vessels on Land or Permanently AnchoredBridges, Aqueducts - Concrete, Including Supports and DeckBridges, Aqueducts - Metal, Including Supports and DeckBridges, Aqueducts - Wood or Part WoodCooling Towers - MasonryCooling Towers - MetalCooling Towers - WoodCordwood, Felled Timber, Stakes &amp; RR Ties in Open, Not on Prem of a Lumber Mill or Bldrs Supply YardCranes and Other Heavy Machinery in the OpenDrive in Theaters (Speakers and Screens Only) - Screens - ConcreteDrive in Theaters (Speakers and Screens Only) - Screens - MetalDrive in Theaters (Speakers and Screens Only) - Screens - WoodDrive in Theaters (Speakers and Screens Only) - SpeakersElectric Transformers in the Open Not Owned by a Public Utility - on Concrete Pads or Steel SupportsElectric Transformers in the Open Not Owned by a Public Utility - on Wood SupportsElectric Vehicle Charging Stations (Pole Mount or Pedestal; Not Wall Mounted)Exhibit Stands and Booths in the Open - Entirely MetalExhibit Stands and Booths in the Open - Wood or Part WoodExplosives in the OpenFences and Arbors - Metal or MasonryFences and Arbors - WoodIncinerators or Refuse Burners Which Are Not Part of a Building - All Other ConstructionIncinerators or Refuse Burners Which Are Not Part of a Building - Masonry ConstructionMachinery and Equipmt in the Open - Procg Combustible Materials Other than Hay, Straw or FibersMachinery and Equipment in the Open - Processing Hay, Straw or Other FibersMachinery and Equipment in the Open - Processing Non-combustible Materials OnlyMotion Picture Sets in the OpenNursery Stock in the Open - Trees, Shrubs, Plants, FlowersOil DerricksOther - Masonry or Metal or Other Non-combustible Materials, Stock or EquipmentOther - Materials, Stock or Equipment Which Are Combustible or Part CombustibleOther - Metal or Other Non-combustible Materials W Combustible Wrappings, or on Combustible PalletsRafts and Other Floating Equipment, Also Portable or Movable Docks (Not Boats or Dredges)Reservoir RoofsSawmills, Portable, in the OpenSolar Panel Arrays - Freestanding (Not on Buildings), including strut supportStock Pens, Feed Pens, Feed Storing Pens, Corrals - Not Subject to Division Four - FarmStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - MetalStreet Light Poles, Meters, Signs, Traffic Signals, Flagpoles, Alarm Boxes, Similar Equipmt - WoodSwimming Pools in the Open - Above Ground (All Other)Swimming Pools in the Open - Above Ground (Concrete or Metal)Swimming Pools in the Open - in Ground (All Other)Swimming Pools in the Open - in Ground (Concrete or Metal)Tanks, Bins &amp; Silos - Tanks Above Grnd - Masonry Tanks on the Grnd, Masonry Tanks W Masonry SupportsTanks, Bins &amp; Silos -Tanks Above Grnd -Steel Tanks on Grnd, Masonry or Steel Tanks on Steel SupportsTanks, Bins &amp; Silos - Tanks Above Grnd - Wood Tanks or Tanks W Wood Supports (Incldg Wood Rsv Roofs)Tanks, Bins and Silos - Tanks Below Ground, Covered with EarthTents and Fabric Covered Structures - Air Supported StructuresTents and Fabric Covered Structures - All Other Fabric Covered StructuresTents and Fabric Covered Structures - Supported by Structural Metal MembersTowers - Broadcasting Antennas (Cell, Radio and TV)Towers - Receiving Antennas (Cell, Radio and TV)Towers - Smokestacks or Chimneys (Free Standing) - MasonryTowers - Smokestacks or Chimneys (Free Standing) - MetalTunnels &amp; Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine) - Masonry or MetalTunnels and Undrgrd Passageways, Incldg Undrgrd Conduits or Pipes (Exclg Mine Passageways) - WoodWater or Sewage Lift Pumps (Enclosed or Open) - Metal or MasonryWater or Sewage Lift Pumps (Enclosed or Open) - Wood or Part WoodWind Towers - Windmills and wind turbines - tower base of concrete, reinf masonry, steel constrctnWind Towers - Windmills and wind turbines - other   ')]</value>
      <webElementGuid>703f7b96-d59c-4ff0-a131-2e95d78979f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
