<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_CP1211_Select_TypeOfBurglarAlarm</name>
   <tag></tag>
   <elementGuidId>994777de-bf86-465d-9d93-89550d79c031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a44f271c-329d-4275-a582-1117d1f26c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput</value>
      <webElementGuid>351eb19e-beaf-4bcf-b4ce-1001ae887adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7095d1ac-11ad-4ec5-93e3-e1cda2cbfe74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>85776eab-5028-4544-ac01-3abab9108079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Not ApplicableCentral Station With KeysCentral Station Without KeysLocal Alarm   </value>
      <webElementGuid>40bf5ab1-9274-4ab2-a154-19562bec1764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>de7f8e7b-97ea-45d1-9b3e-495822fc05ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput']</value>
      <webElementGuid>0693a94d-c83b-4c61-b964-9d0f25438d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput']/div/div/select</value>
      <webElementGuid>bffb75fb-1d3e-4ecc-b6d3-103ec355e061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Burglar Alarm System'])[1]/following::select[1]</value>
      <webElementGuid>809e008d-21ca-4e06-b819-f861629b68cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Requirements Description'])[1]/following::select[1]</value>
      <webElementGuid>e8b3d348-3a02-414e-b194-eb7bc0bb9a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type of Watchman Service'])[1]/preceding::select[1]</value>
      <webElementGuid>9fe424a7-e0ad-4b32-a8ff-bd92d484833b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CP 99 20 Contributing Insurance'])[1]/preceding::select[2]</value>
      <webElementGuid>a016a82e-ada7-43bf-aee3-c1ccafd7e24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[48]/div[2]/div/div/div/select</value>
      <webElementGuid>60bbac46-560d-4b3a-ae92-3e5fe7245fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-5-LobCovTermWithPostOnChangeInputSet-OptionTermInput' and (text() = '   Not ApplicableCentral Station With KeysCentral Station Without KeysLocal Alarm   ' or . = '   Not ApplicableCentral Station With KeysCentral Station Without KeysLocal Alarm   ')]</value>
      <webElementGuid>87932c7a-a80f-4fa0-ad19-189c304040ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
