<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_CP9920_PercentOfContributingInsurance</name>
   <tag></tag>
   <elementGuidId>8a47f0b9-b908-44bb-bebe-a571841d4fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8b42068-552b-4fd1-bf9d-46cad14146a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7250e4e-77b7-4c96-97f7-ab117ec0f94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput</value>
      <webElementGuid>0e312ddd-7e45-4de8-b2a4-67926108e497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e95e002-002d-4c22-a67a-b4835248b9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5e314e1a-0ef6-4e54-8c96-31ef4a8bfdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>43450f65-ece5-40f7-8437-74fc15e13f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9cf973aa-9511-484d-8590-91fc29384078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>51432209-4e0f-48e2-ab3e-a96ea56830a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>1bc0ab44-8cf3-494d-ae0a-6cf28f5ff06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']/div/input</value>
      <webElementGuid>00daa2dc-1019-40c5-9e6e-0a299ac96b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/input</value>
      <webElementGuid>4fdcb51b-0d49-4ec6-8dc6-f394c66ef3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>64b901cb-18a2-42a3-ba51-856133dbd351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
