<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CPAddCov_LossOrDamageToCustomersAuto_PC_TextBox_Limit</name>
   <tag></tag>
   <elementGuidId>bcaa400f-a525-40dc-8caa-179506a4600e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ca79388-3613-48fb-954a-e5a51faed904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput</value>
      <webElementGuid>f489f4ae-7bed-477c-b833-7ca251dcf29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-TextValueWidget gw-styleTag--InputWidget gw-ValueWidget gw-editable gw-required</value>
      <webElementGuid>aacfd77c-263c-4468-9c84-4bc76b6a35ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-change</name>
      <type>Main</type>
      <value>refresh</value>
      <webElementGuid>3bbf7ecd-1125-41e4-b9ba-5fba4a69f90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-getset</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35694367-6bd1-4210-b112-aa3a3d24640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-entry-value-ids</name>
      <type>Main</type>
      <value>1,3</value>
      <webElementGuid>8e5ddbd9-a09f-4e17-9725-94c7d104b5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput&quot;)</value>
      <webElementGuid>c919b4dc-269f-4e36-a090-98c8dc84fca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput']</value>
      <webElementGuid>2fa056a6-0856-428a-91a0-371c39e36046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput_Input']/div[2]/div</value>
      <webElementGuid>b71118e7-6329-4ae6-b8e9-83066c49250c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[1]/following::div[2]</value>
      <webElementGuid>70fb3edc-7a2e-472e-97b7-0569c5f24ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Windstorm or Hail Deductible'])[1]/following::div[16]</value>
      <webElementGuid>89091396-a9d2-4ba6-9f88-009e173355af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cause of Loss'])[1]/preceding::div[9]</value>
      <webElementGuid>b740413d-0ecb-4329-ae31-dc7e59225fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special'])[1]/preceding::div[10]</value>
      <webElementGuid>1ce1c43f-e2dc-4c2f-8bf8-d08f40381ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[24]/div[2]/div</value>
      <webElementGuid>4ddfb54a-ab67-445b-8e50-845623da7b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CP7BuildingPopup-CP7BuildingCV-CP7BuildingCoveragesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-LobCovTermWithPostOnChangeInputSet-DirectTermInput']</value>
      <webElementGuid>c09245c3-1c45-40cc-b4af-6f96892a97bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
