<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Common_PolicyInfo_Dropdown_TierClassification</name>
   <tag></tag>
   <elementGuidId>3d0dfb0f-4154-4a6d-b583-42122cb5fe25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>949fa12a-fe13-4ba1-a4c0-f884909e11e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier</value>
      <webElementGuid>a7cbcb38-7fb7-4eea-8f66-19cbc7ee2d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>566d427b-f20c-4bfd-86b4-3be5f80ead45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>b5074b66-123d-465d-8ead-b35d3c7cb179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Tier 1Tier 2Tier 3Tier 4   </value>
      <webElementGuid>de4af863-af71-4f56-8d43-443b692410d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>e481a448-a392-4c0e-b1d8-ba722f88a340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier']</value>
      <webElementGuid>acd2675a-ae7c-44fd-973a-175b1fdf3e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier']/div/div/select</value>
      <webElementGuid>ad86bee5-4e62-4b6e-bbf0-e39a712b7d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tier Classification'])[1]/following::select[1]</value>
      <webElementGuid>a174f603-95db-4ee0-a85d-47e383469a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate as of Date'])[1]/following::select[1]</value>
      <webElementGuid>f4c5694b-6093-4731-bcc7-a6b74176d766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origin Date'])[1]/preceding::select[1]</value>
      <webElementGuid>ab48770f-fe16-42e2-9159-5acee6397de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facultative Reinsurance'])[1]/preceding::select[1]</value>
      <webElementGuid>02c9705b-4dd4-41a0-bce7-49839f3de11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/div/select</value>
      <webElementGuid>0c41e740-b5ec-4719-b4db-4ec68dd98b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'RewriteWizard-LOBWizardStepGroup-RewriteWizard_PolicyInfoScreen-RewriteWizard_PolicyInfoDV-PolicyInfoInputSet-RatingTier' and (text() = '   Tier 1Tier 2Tier 3Tier 4   ' or . = '   Tier 1Tier 2Tier 3Tier 4   ')]</value>
      <webElementGuid>2d2393e6-35f6-487e-a056-314856fb61aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
