<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP1509OrCP1508_ScheduleTextBox_Address</name>
   <tag></tag>
   <elementGuidId>f2ad11f1-1003-48d9-8cf0-8d9e2d693b8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name='CP7SpecialClassBusinessIncomePopup-CP7SpecClsBICV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-7-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-StringValue']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
