<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_CP9920_Schedule_AdditionalCoverage</name>
   <tag></tag>
   <elementGuidId>9218bc93-dd2d-4f35-855a-04f974dc4d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>08f620d7-15b0-4e2c-938f-7e7731463020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42d20f87-e97d-439e-bb2e-bd57be53c34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue</value>
      <webElementGuid>c24d59c2-a414-49ed-9177-166b747b2495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>ed97cc1b-333c-4da6-96e6-6614a82755f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7e8124a-4c62-456f-9dc3-f537ec1a221c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue&quot;)/div[@class=&quot;gw-vw--value&quot;]/textarea[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>11623c87-b21e-4a75-b69b-211468b15234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue']</value>
      <webElementGuid>08639098-d0fe-472f-9db6-bd17ba31a1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue']/div/textarea</value>
      <webElementGuid>ef78d19e-818a-4933-bc8f-a1edca601455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Limit'])[1]/following::textarea[1]</value>
      <webElementGuid>f4f24d6e-0dfe-4dde-8df6-f2cf5129745e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Coverage'])[1]/following::textarea[1]</value>
      <webElementGuid>35a80fbc-5a62-4665-a34d-e1c6d0244df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>687a1d08-ff10-4666-ace7-12cf581ec89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3a85c0e9-1a30-4ce5-ac6e-cb994d444fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-LobScheduleInputSet-LobScheduledItemsLVInputSet-LobScheduledItemsLV-ScheduledItemsIterator-0-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-TextAreaValue' and (text() = '0' or . = '0')]</value>
      <webElementGuid>103f9410-8be3-4e37-a49c-08b3762b9014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
