<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_CP9920_YourBusinessPersonalProperty_TotalLimit</name>
   <tag></tag>
   <elementGuidId>07c8379e-8ca0-4b3f-8d0e-a9c850d736a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>366b72a2-6cc5-4710-97fb-dddc1766808b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee2550ff-9b7d-476e-9d55-fd121a066ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput</value>
      <webElementGuid>f3f7ad29-229e-40d0-b805-cab708f72f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45e3add1-040b-4aa1-8276-cbff79b4f707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbba429b-dc36-4d43-8880-454831bc775b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b6935d48-aeca-4f93-ab3f-36965508b422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>21eb357b-7386-445c-9a6a-c19a81cf6f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>73fae554-c499-4c44-bf35-073310313126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>20dd5556-b41f-424e-bc51-53c2d31a1a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>5b72ac39-f341-4954-a64e-46c9fd8f9bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']/div/input</value>
      <webElementGuid>200ff491-4610-4fac-abf1-e19babf94b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div[2]/div/div/input</value>
      <webElementGuid>d39ff667-b320-4d4c-bc94-81100e4bbee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CP7BuildingPopup-CP7BuildingCV-BuildingLevelExclusionsAndConditions-LobExclusionsAndConditionsPanelSet-ConditionsPanel-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-2-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>66a7e335-a870-40ef-b551-de3978648d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
