<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Common_Dropdown_AddressType</name>
   <tag></tag>
   <elementGuidId>cfca08f8-0532-47e3-9a21-44c350dfb18c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'AddressType')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d607870e-ac4d-4861-9651-efa473c2ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType</value>
      <webElementGuid>a9d1cfa0-81d6-4a1e-adba-56e3fd594571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32670042-3b31-4c49-be09-e989e3649cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>8581f09c-2980-470b-b4f6-16dd640538d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>BillingBusinessHomeOther   </value>
      <webElementGuid>2feb8335-9c71-475e-83a0-3af4b93303c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cc5de86a-55af-4afb-8771-9b6e5d2a847e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType']</value>
      <webElementGuid>f5528e07-9119-4ba6-8be8-1af7e06bc59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType']/div/div/select</value>
      <webElementGuid>9e3e5751-6a65-4564-a85a-404894afb3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Type'])[1]/following::select[1]</value>
      <webElementGuid>76159167-e158-4019-ba1f-8c9e8d34c9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Results'])[1]/following::select[1]</value>
      <webElementGuid>f6f50845-f095-4172-8553-1b929f29dee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>d33c9ba7-75b1-4338-a71b-fbd3ed49e793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legal Entity'])[1]/preceding::select[1]</value>
      <webElementGuid>489a217e-0008-4c9a-94de-b5ce3b7b5dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/div/div/div/select</value>
      <webElementGuid>d0f715cd-3afc-4127-a09a-6a14d4a8251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CreateAccount-CreateAccountScreen-CreateAccountDV-AddressType' and (text() = '   &lt;none>BillingBusinessHomeOther   ' or . = '   &lt;none>BillingBusinessHomeOther   ')]</value>
      <webElementGuid>e7a768dd-e804-4ee4-816d-a16e207829e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
