<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_CP_AddCov_LossOrDamageToCustomersAuto_Dropdown_Type</name>
   <tag></tag>
   <elementGuidId>1d748b4c-5001-4329-98ab-41f71ae51c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a4d5cd95-6222-443b-a263-d46f22939b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput</value>
      <webElementGuid>f1218daa-495a-439b-94c5-8f34622b2a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>62832322-c173-46cc-9e93-d70f7cb55a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>a52e4059-1a89-41be-8c86-71a6655e2031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Direct Primary CoverageActual Loss SustainedLegal Liability Coverage   </value>
      <webElementGuid>254c7cfb-7a93-40bf-ac1f-c9e49cffa485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>60135012-b8b4-4537-823b-761e80bb8aa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput']</value>
      <webElementGuid>040048ae-95d7-4a74-86d4-9f2e00c89681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput']/div/div/select</value>
      <webElementGuid>157007fe-0405-497b-8d78-d39cebdffee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>04aa0460-2ad0-4d05-8dba-ab24d7d932e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Loss or Damage to Customer', &quot;'&quot;, 's Auto')])[2]/following::select[1]</value>
      <webElementGuid>285f719f-8d99-446c-b58b-005dc989ef58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible (OTC-Each Auto/OTC-Any One Event/Collision)'])[1]/preceding::select[1]</value>
      <webElementGuid>91485881-af3a-4374-92cd-edee24ccb725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EQUI2060 Equipment Breakdown'])[1]/preceding::select[2]</value>
      <webElementGuid>4fded525-8785-49f7-bcb3-9fe22eb0ee8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3c0d3ce0-4564-464f-968e-d6915b432c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CP7BuildingPopup-CP7BuildingCV-LobAdditionalCoveragesPanelSet-LobClausesDV-0-LobCoverageInputSet-CovPatternInputGroup-CovTermIterator-0-LobCovTermWithPostOnChangeInputSet-OptionTermInput' and (text() = '   &lt;none>Direct Primary CoverageActual Loss SustainedLegal Liability Coverage   ' or . = '   &lt;none>Direct Primary CoverageActual Loss SustainedLegal Liability Coverage   ')]</value>
      <webElementGuid>d1394aff-bcef-433e-b347-c516ed1a22a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
