<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Exposures_TypeList_Location1</name>
   <tag></tag>
   <elementGuidId>aa4a7ec1-0de3-49b5-a1c8-0572ba4a391e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0fc0722a-bff0-43ff-a3a5-41cf178fc83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location</value>
      <webElementGuid>8bfb6bb4-1b2b-4f91-b2ca-f406d2bda238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61cd7624-2076-42d5-92ae-b87a795a076b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>c0ffa8ad-e320-48ce-92a8-a5873b2c621d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>1: 69 Washington Ave, Cicero, IN   </value>
      <webElementGuid>1411dfc4-45a3-4c9a-94b3-b526648a39ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>fcb9efcc-5d38-4450-a78b-e926d6115d75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location']</value>
      <webElementGuid>c24dccb0-b4d2-4c6e-b38b-5240627ed2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location']/div/div/select</value>
      <webElementGuid>44fcd648-23be-45a0-ad82-74098d37b4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location'])[1]/following::select[1]</value>
      <webElementGuid>13c6a62d-7e02-461b-bfa8-d0d7bdebde78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverages'])[1]/preceding::select[1]</value>
      <webElementGuid>131012ba-9096-44fd-9943-b044c3919d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'GL7ExposurePopup-2', '&quot;', ')')])[1]/preceding::select[1]</value>
      <webElementGuid>596463a3-01bc-41e6-ac50-4ab475e53e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>de2af523-5b03-48c9-bb65-e2b10ab85ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'GL7ExposurePopup-GL7ExposureCV-ExposureDetails-Location' and (text() = '   &lt;none>1: 69 Washington Ave, Cicero, IN   ' or . = '   &lt;none>1: 69 Washington Ave, Cicero, IN   ')]</value>
      <webElementGuid>23c9ac76-199d-4615-98fd-52141ef3a76e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
