<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EquipmentSalesAndRental_InsideAndOutsideBuilding_ScheduleDropdown_EquipmentYouLeaseOrRentToOthers</name>
   <tag></tag>
   <elementGuidId>af6b66bd-2efd-4cc9-a229-0aa751029570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c29af7e5-4289-49cb-94bd-c3d24feeacdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell</value>
      <webElementGuid>9d0ec4ee-25ec-44ed-bf03-0306b2f6e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02b4216e-276e-4977-8051-e61d47018e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>14d7b591-7626-429d-b20b-671599544581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>4fc79e61-3f52-422b-96f1-c356d2393a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cd4fef67-e1b6-43bc-8033-d2f0e50f073b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell']</value>
      <webElementGuid>f91b8206-5906-43c8-8135-959458d09398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell']/div/div/select</value>
      <webElementGuid>3e947c01-4a59-4ed3-9a82-557387b17a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[2]/following::select[3]</value>
      <webElementGuid>194ae7c1-cbbf-4d78-a4f2-5c345aef8a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[1]/following::select[3]</value>
      <webElementGuid>815b5844-6b0b-4642-b245-5f1d48aee28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment Sales and Rental - Separate Limit Coverage'])[1]/preceding::select[8]</value>
      <webElementGuid>ca4b09f6-9a0f-4591-a4b7-66af1fdabb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::select[8]</value>
      <webElementGuid>659129a7-4097-4b19-926f-7514a62197b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/div/div/div/div/select</value>
      <webElementGuid>5b167e29-c7e8-4bdd-854c-7e70388be869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRentCell' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>481a3f96-bd60-4a77-b64d-83221f189a2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
