<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EquipmentSalesAndRental_SeperateLimitCov_ScheduleTextBox_EquipmentYouLeaseOrRentToOthersLimit</name>
   <tag></tag>
   <elementGuidId>7ce1aa41-da6b-4f9f-87f8-4950e29cca41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7de1103-5cd0-49d6-b7b2-4b49797122c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a6d8730-f655-44ee-b981-e7579cde6c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit</value>
      <webElementGuid>8c5e9948-b311-4d47-be4b-a90c6dd47acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e7b9629-4814-470b-aece-82449a430046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>56524be0-4e25-44d8-be08-f8c16a7414b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>2d2fb3ca-f1e5-43b4-bdb9-32fe4686518e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5d3c2791-b9a9-4cfc-94d8-9fcf27843b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>0de12c3a-d4a7-49bd-ae0d-6b4620d043bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit']</value>
      <webElementGuid>e7edcfb0-9f2b-42f3-be78-1818142d1a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit']/div/input</value>
      <webElementGuid>cb929475-b454-4f2c-9247-4e5e494c3b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/div/div/input</value>
      <webElementGuid>cd83c08d-0396-41c1-b13f-8075e60cf4d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-rentLimit']</value>
      <webElementGuid>81bc92e2-b85b-4145-a493-cffbea70b24b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
