<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Exposures_Button_Search</name>
   <tag></tag>
   <elementGuidId>5b1d39cb-2e70-49cd-aa7d-77a5a7ad9b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'ClassCode-Search')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode-Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>314570bc-791a-4228-bbb1-885440a196ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode-Search</value>
      <webElementGuid>057b26b1-5ff0-4057-8107-e2d4da5f801a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-PickerLinkWidget gw-styleTag--ValueWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>506b1a31-e715-4f62-9631-ceb68dd46de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>95c70d11-87ab-44a2-b2b3-61231e01e16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>6faf6ae4-b994-4b67-a6b3-fd90051acf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c836ac54-fd15-4c63-8211-649cda7c6d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d45b7988-6c6a-46dc-b6a1-06bbbe1f0c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode-Search&quot;)</value>
      <webElementGuid>08ec3082-7455-446b-93de-413217eb1232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode-Search']</value>
      <webElementGuid>acf6dc21-d60c-455f-a60d-d70c98e0e138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode']/div[2]/div</value>
      <webElementGuid>a910369c-dcef-413d-b934-7690353b0a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Code'])[1]/following::div[7]</value>
      <webElementGuid>5a96e242-2f5b-4b54-b77a-81d15cdcddd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::div[13]</value>
      <webElementGuid>19c96ded-810c-4909-9865-6756ad2d94a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Description'])[1]/preceding::div[1]</value>
      <webElementGuid>a68b685e-9301-4057-8f33-7a36361e5b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufactured Home Communities'])[1]/preceding::div[2]</value>
      <webElementGuid>53675731-023b-4745-9f45-8c49a7e9067c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/div</value>
      <webElementGuid>071d0ebd-7647-4ac2-9026-fbe98d250722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'GL7ExposurePopup-GL7ExposureCV-LobEntityDV-1-LobInputSet-LobInternalInputSet-ProdClassCode-Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>83581464-2ed5-450a-a496-8ceacae4ad40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
