<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EquipmentSalesAndRental_SeperateLimitCov_PropOutside_ScheduleTextBox_PartsAccessoriesFluidAndLubricationSuppliesAndTiresLimit</name>
   <tag></tag>
   <elementGuidId>ec57be97-ddfe-4f94-b428-56c3e279747d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5540a252-039a-4650-b34c-4e64e171dc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc164fcb-c9b8-49cd-b52b-d4b60bf3cd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell</value>
      <webElementGuid>d28f66a3-0616-4928-b360-3a206750bef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d81ef77d-930c-44ce-bfc0-ae3789bf71da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6ed13a1c-64f7-4e81-9513-04491e1bb5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>2bf56452-fad0-4bb8-922e-1733b912ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5ec1190a-af19-4868-b096-3a78668b564c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cd4a0413-c126-4752-b6fe-9b2fe90c8950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell']</value>
      <webElementGuid>b4fdeb41-ef60-4ae6-acef-0c27dc9c92db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell']/div/input</value>
      <webElementGuid>4e350b40-32ac-4035-8ddd-b9ff58b28525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[23]/div/div/div/input</value>
      <webElementGuid>49181b1a-3e37-47aa-bde5-645b3fcd1403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-PrtAccFludLUbSupplyLmtcell']</value>
      <webElementGuid>73fcec69-7610-4ac4-9f69-23d344f647f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
