<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EnterAccInfo_Button_StandardizeAddress</name>
   <tag></tag>
   <elementGuidId>c0aec657-c2c1-45dc-84d0-a089dfaf65ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CreateAccount-CreateAccountScreen-CreateAccountDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-StdAddressIS-standardize']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus > div.gw-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0c05797-5625-4d31-a736-a8e20a55f68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>95304376-f771-4b15-91f5-d0376039179d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standardize Address</value>
      <webElementGuid>af8e1860-98c0-43a5-a8a5-10782583898e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CreateAccount-CreateAccountScreen-CreateAccountDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-StdAddressIS-standardize&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>63b8a40b-afeb-4f09-aac8-50b904cbc660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CreateAccount-CreateAccountScreen-CreateAccountDV-AddressInputSet-globalAddressContainer-GlobalAddressInputSet-StdAddressIS-standardize']/div/div[2]</value>
      <webElementGuid>fca40ece-2188-42d8-8ee4-1789e4d2a230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SA'])[1]/following::div[1]</value>
      <webElementGuid>55a69e5b-4719-4c19-aa1d-f5aed6394046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Standardized'])[1]/following::div[13]</value>
      <webElementGuid>12712d45-7df7-4d86-b447-97a699c45fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ov'])[1]/preceding::div[1]</value>
      <webElementGuid>96d6dfa7-7d21-473f-beae-cc7f408d89ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Override'])[1]/preceding::div[3]</value>
      <webElementGuid>ff59e4d3-19a1-41cd-96cd-7669cc9b125c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standardize Address']/parent::*</value>
      <webElementGuid>99d5ddc2-bd46-43f6-88ce-b2666fca1981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div/div/div/div/div/div/div/div[2]</value>
      <webElementGuid>fd62f7fd-2455-4b71-8e31-17b057bb0b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Standardize Address' or . = 'Standardize Address')]</value>
      <webElementGuid>eb0aa421-16f3-455d-b9ab-851c195a9283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
