<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Exposures_TextBox_ExposureValue</name>
   <tag></tag>
   <elementGuidId>a273e76f-bcbc-441a-8587-2031326d15f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Exposure']/..//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8ba2a9d-e0fa-4f05-9a6f-3d24fa564627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba8f68cd-8d7c-4e85-8fb3-abc78e53ad55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input</value>
      <webElementGuid>2f1a2773-ee11-4e99-9515-f63617938b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2bcbe705-2dfd-43f0-b092-ad5c018891c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc7982f0-26aa-494c-9370-d22d79e2fb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a2cdc615-2dee-41f0-8c60-c0f05883b413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>7f1f267b-f380-486b-bf1e-539727c85203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>22d626ca-138b-47fd-aa01-092f019b5976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>55c5af58-0de4-406f-9bda-ad9cb0283e54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>a0aa7645-19b8-467a-b555-cff5a1477cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input']/div/input</value>
      <webElementGuid>ff108f6b-5987-4524-b907-9118049b43cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div[2]/div/div/input</value>
      <webElementGuid>5017cbcd-462d-4020-aa0e-69a2af69fef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'GL7ExposurePopup-GL7ExposureCV-LobEntityDV-48-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>cba7015f-f7a6-4d21-9378-7d07613a6c84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
