<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EquipmentSalesAndRental_InsideAndOutsideBuilding_ScheduleDropdown_EquipIntendedForSale</name>
   <tag></tag>
   <elementGuidId>765801df-0aeb-457d-a8f8-bbbc66b83989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bce67b07-f8ea-4f4e-9d49-e4cc02cf4421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1</value>
      <webElementGuid>5aa75504-5c5d-4d56-b4c6-42e7c82812f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6783af8d-993c-4b73-97c6-644e6b4f61d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3e9f0fe6-1037-41dc-ba69-607d1aaaa741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>5de9a239-6b89-4eca-8e9c-5e39ad9157ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>9d7b6225-9499-4a9c-930f-28b73e4db9d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1']</value>
      <webElementGuid>c7534d50-0fdb-4070-9b11-a73f8116a3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1']/div/div/select</value>
      <webElementGuid>e8245ae0-c88e-484b-956d-394097febd4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[2]/following::select[7]</value>
      <webElementGuid>684b407f-bbe9-4cf7-8efb-6a6218ee87de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[1]/following::select[7]</value>
      <webElementGuid>7106b873-541f-4ecc-b061-433dcc01520e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment Sales and Rental - Separate Limit Coverage'])[1]/preceding::select[8]</value>
      <webElementGuid>63f29811-6c82-47a1-961e-a490a51bd62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::select[8]</value>
      <webElementGuid>0d1e027c-e045-40c7-984d-9267ff615f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/div/div/div/div/select</value>
      <webElementGuid>46d4ae28-9659-47ad-af85-486cc3bb69b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipSaleCell1' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>6c146e27-350f-48c5-a4e1-7855509e9587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
