<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_EquipmentSalesAndRental_SeperateLimitCov_ScheduleDropdown_EquipmentOfOthersYouAreRepairingOrServicing</name>
   <tag></tag>
   <elementGuidId>621f0c70-67a4-4511-8e1d-a3514f827134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>984291c2-9594-4f03-9b4d-5e54ff3a2204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell</value>
      <webElementGuid>0885d857-5f6e-48b0-9654-f208220ad8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>78e28e76-eaf1-4b35-aa6a-e1c0fa148175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>1e278ac3-e09a-40fc-8944-262490f4814a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>a4db7c33-f6df-407d-9ee5-6dee028df293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>30f8209b-b3c6-413f-b351-b02319be7b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell']</value>
      <webElementGuid>1fce0bb4-712a-44d3-a308-a2ca5040c9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell']/div/div/select</value>
      <webElementGuid>afb2574b-e560-46e4-a6ac-2867805847ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[2]/following::select[4]</value>
      <webElementGuid>48d454d4-2d1f-4304-82aa-3c8dfbdbb2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New/Used'])[1]/following::select[4]</value>
      <webElementGuid>5fc895ad-f8be-426f-a431-3fa5c05415bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::select[7]</value>
      <webElementGuid>0ed59fc3-d844-4dc6-806f-12c676341703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[3]/preceding::select[7]</value>
      <webElementGuid>0b164194-27d7-4875-b4c1-fc153f5bf757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/div/div/div/select</value>
      <webElementGuid>cf992d8b-d559-4929-bf66-87bcacb5eaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7EquipmentSalesandRentaPopup-IM7EquipmentSalesandRentaPanelSet-ESnRSepaLmtCovClauseCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-eqipRepairCell' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>c01f117b-960f-468a-bfc1-45a7eed1b7ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
