<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_GL_CG2142_Dropdown_ExcludedHazards</name>
   <tag></tag>
   <elementGuidId>5f9288ec-0bd1-4533-a7ef-81a88e42e9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'${CG2142_ScheduleIndex}-1-UnvalidatedScheduledItemColumnInput-LobScheduledItemColumnInput-RangeValue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
