<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_FineArtsFloater_Dropdown_Deductible</name>
   <tag></tag>
   <elementGuidId>cb6a16c6-663d-4102-893c-3987c91a4671</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9a678f4-f089-4870-9f9e-b7aa6aa8fd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible</value>
      <webElementGuid>9d3c9cee-43c6-49fe-83cc-e37494b41263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9fd9a6f8-6bd9-4f53-abc1-e8cd5010e81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>87c82dbd-9660-4c78-b7c6-884eb8fdc9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   2505001,0002,5005,00010,000   </value>
      <webElementGuid>9ee5e4b1-0372-4f0b-8b89-4547d9039510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>ca7717ce-c8c6-4651-bbea-045b98edf2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible']</value>
      <webElementGuid>6ff92a5e-396c-41c1-9681-4e81016b20a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible']/div/div/select</value>
      <webElementGuid>196d83c0-28f0-4a4d-a740-3364e1e648d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[1]</value>
      <webElementGuid>94d8a3ee-2695-4aab-98f7-f2cb829ef88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catastrophe Limit'])[1]/following::select[1]</value>
      <webElementGuid>a17f2200-78f3-40d5-90b4-b0faa81fc605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fine Art Floater Coverages'])[1]/preceding::select[1]</value>
      <webElementGuid>74ecfb55-2317-49ec-96db-9a4d586c7ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IM 7400 Fine Arts Coverage - Fine Art Floater'])[1]/preceding::select[1]</value>
      <webElementGuid>05d0bfb7-830a-4a21-92b9-e33d81782936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fb70fcf4-9957-4cda-a35b-7e3fb5705cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFDeductible' and (text() = '   2505001,0002,5005,00010,000   ' or . = '   2505001,0002,5005,00010,000   ')]</value>
      <webElementGuid>c3e4a0b9-d218-4e1b-ac84-49af8acca634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
