<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_InstallationFloater_IM7100_LengthOfJob</name>
   <tag></tag>
   <elementGuidId>482184ba-3401-470f-bce1-07bf84bee497</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e435a4b2-4cc9-4261-9580-1065ebcf91d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae31c938-e37b-4f5f-a51f-351a0f79edee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob</value>
      <webElementGuid>405a5c20-80d9-49e4-a92f-94c466b64137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b3df5f24-e392-4d3c-b7f4-aa348c0709ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d8519727-29a9-46a7-8ac7-c262b2275c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>d51cabaa-2994-4b27-9c97-6f7f25b4704d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5cec3997-0ec0-4d64-b395-fcc13866568d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>03c96b91-b7c7-48a3-a5c4-dc542d6754e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob']</value>
      <webElementGuid>d037ac4b-b729-4d5a-a6fe-54f5bd8e02eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob']/div/input</value>
      <webElementGuid>827d7419-6f4f-45e8-bb38-840e683873bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/input</value>
      <webElementGuid>e8519dd4-2ee2-4653-b014-24059cd180c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-IM7IFCovSchedIFCovSchedLengthofJob']</value>
      <webElementGuid>8e2259b1-7ad7-4215-baec-a474dceece3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
