<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellaneousFloater_IM7505_CatastropheLimit</name>
   <tag></tag>
   <elementGuidId>4d68850d-8948-4f38-9bba-3f19b9f1dd33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21da2a87-5496-4bc4-8184-d7cce0ae0622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fb74727-d464-411b-a555-c2d45725dc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell</value>
      <webElementGuid>282ad87d-95e1-4613-9cb4-eb79b70c1a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68745a57-2f99-4db5-b948-1d594ce7649b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ae1b17ed-86f3-47f3-95c4-c85e9cf23b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>37fcb550-cf47-4196-8cbf-1afb05b23d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3bbf594a-3967-4ce9-b449-31e1cb305e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>129ce58a-6a64-439f-bfc6-2d425bf49246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell']</value>
      <webElementGuid>a03a9c8f-c756-46b6-9aee-2d5dca5d340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell']/div/input</value>
      <webElementGuid>1b79ab6f-be06-4806-b23c-25c6a9f75dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>98f6a644-0784-4bae-9000-e07bf1f43363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-CataLimitCell']</value>
      <webElementGuid>18c3c579-9f46-4ac2-903e-24a99edcdf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
