<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_BuildersRisk_IM7980_Dropdown_Coinsurance</name>
   <tag></tag>
   <elementGuidId>3e60513d-6401-45de-b01d-1dfbb4b1bcbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9362233f-403e-44b9-b6b0-894b08708079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance</value>
      <webElementGuid>195ca7d9-996d-4ef0-bd5a-9dbbe3bf21d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9170451-2f9a-48d0-aea5-08673934c416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>62275057-0c91-4ba8-94f4-0dc3a3d76564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>80%90%100%Waived   </value>
      <webElementGuid>876aa226-d17a-4e88-a39c-de9807b5ca42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>c9778473-6543-4c67-ac57-66d1c86f82cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance']</value>
      <webElementGuid>e2985477-095a-467b-8c12-8257f15fa91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance']/div/div/select</value>
      <webElementGuid>01bda4f4-0970-4fe7-9b7a-dabe2231b771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coinsurance'])[2]/following::select[1]</value>
      <webElementGuid>f9b1ed51-f472-4db6-a42d-8a2d6490b5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[2]/following::select[2]</value>
      <webElementGuid>cf1d0b9f-6849-4825-8399-f9cd72bd2cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[3]/preceding::select[1]</value>
      <webElementGuid>20b68d85-606b-424c-adf2-3bd4d02d981f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::select[1]</value>
      <webElementGuid>864e78af-a6f4-4957-909b-865fabd4dae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/select</value>
      <webElementGuid>3b7f2aaa-52a8-48c6-8ec9-68c50e2407b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-IM7BRCWPCoinsurance' and (text() = '   &lt;none>80%90%100%Waived   ' or . = '   &lt;none>80%90%100%Waived   ')]</value>
      <webElementGuid>e225e2c0-fef9-4382-90b3-26c3394a73e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
