<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_Transit_Checkbox_IM7252TripTransitCoverage</name>
   <tag></tag>
   <elementGuidId>24703391-6cd2-4706-bb35-d32e5496a59d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9c9ed04-509a-4a01-958a-cb103ab70776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>428a4a3c-43a5-45f3-9959-2f3815895f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9a400524-47b9-440a-a521-d2fb3e5b8d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>IM 7252 Trip Transit Coverage visibility toggle</value>
      <webElementGuid>6c2f17b0-3753-4ee0-bbc9-a4f826101e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5ac745cd-c7c7-4972-9508-26f30303692d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>23c898d8-37db-41a8-88e2-9ddd7a2c0e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>4cc56583-ea2f-4065-bbc5-63b92f02e849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>97cfc6b4-6d21-475f-a612-4fe93edf87b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>7bd52f03-7795-4617-8319-881916556540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>87a67652-5a9a-4dd3-bb83-3a3ebe3fe416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
