<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellameousForms_IM7341_DroneEquipmentCoverage</name>
   <tag></tag>
   <elementGuidId>92caad0c-8b6a-45c4-a487-e24cd0c50ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c93571d5-1987-4f3b-b7dd-6d41167a900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE</value>
      <webElementGuid>7b3abe21-7681-4fba-9298-e1195c8f156f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44d90c32-588b-4ce5-8031-09bbf9a5fd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4d0ca1cd-839c-42af-8466-05fde6406048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Coverage Not ProvidedBlanket Drone And Ground EquipmentScheduled Drone And Ground Equipment   </value>
      <webElementGuid>23be4623-b606-4bcd-a214-4cbacc620c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>815b4db9-f879-4659-93d7-64b325233ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE']</value>
      <webElementGuid>83444e9f-4f70-4bb5-8ff9-088c253998cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE']/div/div/select</value>
      <webElementGuid>d70d9be4-3106-4a79-aff3-1a321e0d7129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone And Ground Equipment Coverage'])[1]/following::select[1]</value>
      <webElementGuid>fe48fd31-0d82-469a-9fd9-94f73e76f156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone Coverage Valuation'])[1]/following::select[2]</value>
      <webElementGuid>010285c2-bde2-4c4e-b583-e08f96df714e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone and Ground Equipment Coinsurance'])[1]/preceding::select[1]</value>
      <webElementGuid>2311c856-e467-4646-a543-8e8d7ffb1c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone and Ground Equipment Coverage Valuation'])[1]/preceding::select[2]</value>
      <webElementGuid>cfa731e4-bc64-4d25-80e3-5a2a41db98f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/div/select</value>
      <webElementGuid>700478dd-e190-49b1-8fca-33a2a67b1a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDnGE' and (text() = '   &lt;none>Coverage Not ProvidedBlanket Drone And Ground EquipmentScheduled Drone And Ground Equipment   ' or . = '   &lt;none>Coverage Not ProvidedBlanket Drone And Ground EquipmentScheduled Drone And Ground Equipment   ')]</value>
      <webElementGuid>db9fd30a-b9f0-4fd3-98f5-3c35df356301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
