<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_LocationInformation_Button_OK</name>
   <tag></tag>
   <elementGuidId>74170bae-f6a1-4fd7-89ef-52ee3de0dc8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='IM7LocationPopup-Update']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus > div.gw-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d29729f-eb4f-44de-b37f-ac5f0516bee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>7e7ad423-c748-41d7-a390-2000cc5f998a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>be47d8eb-c329-4395-81f8-fd7d648b2712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7LocationPopup-Update&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>a5e058e6-8a6e-4c78-b539-20b2acc39524</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7LocationPopup-Update']/div/div[2]</value>
      <webElementGuid>787e34f4-8db5-4c7c-9ebc-6efbfdabf445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::div[1]</value>
      <webElementGuid>0d2a3498-28de-4b37-b2bc-dba3d3970ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Accounts Receivable'])[1]/following::div[6]</value>
      <webElementGuid>a3b6470a-73c6-4aad-aa47-089a58eb1dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ca'])[1]/preceding::div[1]</value>
      <webElementGuid>4486b186-d365-49a0-8121-c9530fb94b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]</value>
      <webElementGuid>a1c4cdd0-7a1a-4cc5-9008-b74effaba36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>18ff79d8-3928-4921-8d58-484dc2083e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
