<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_IM7315_Deductible</name>
   <tag></tag>
   <elementGuidId>f3ae8af4-f30e-49bf-a860-c869673860a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>729d85a7-f453-4efb-a26e-ce56e4551676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible</value>
      <webElementGuid>0f9915cf-795f-4af8-9a89-bb62e0126c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ed3c2906-77cc-4903-b76c-e5f8f6ca96c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>dd309e63-d9b0-42ee-89a9-2aff25534437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   2505001,0002,5005,00010,00025,000   </value>
      <webElementGuid>46038825-0c56-4312-bbbc-06ed3c5df826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>f015896c-40f9-4036-a7ab-4a3aba6cefbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible']</value>
      <webElementGuid>55c7034b-3691-48cc-9831-643216ebab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible']/div/div/select</value>
      <webElementGuid>7cf2f9f7-fac0-4b8c-a22f-18465275fd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[1]</value>
      <webElementGuid>71f214e8-e926-4e21-943c-00caf16553de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IM 7315 Cold Storage Locker Coverage - Special Perils Form'])[2]/following::select[1]</value>
      <webElementGuid>85742331-a984-469e-b13f-ed9dfad11f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change In Temperature Or Humidity Coverage'])[1]/preceding::select[1]</value>
      <webElementGuid>b6b0fbb6-db01-4db6-b6d8-032c780a4e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[2]/preceding::select[2]</value>
      <webElementGuid>20997e47-b02a-427c-8d3a-4c36a6919af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3e6f8979-1705-49ac-9b3f-04768b4650e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-3-CoverageInputSet-CovPatternInputGroup-IM7MiscFColdStrgLSpclPCovDeductible' and (text() = '   2505001,0002,5005,00010,00025,000   ' or . = '   2505001,0002,5005,00010,00025,000   ')]</value>
      <webElementGuid>23ecac46-ab83-4c2e-8c1a-24d25485776e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
