<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_PhotographicEquipment_ Blanket_TextBox_BlanketLimit</name>
   <tag></tag>
   <elementGuidId>95d2daaf-8dc1-4f1d-ab1b-8932fae9e0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae38080a-57ea-475f-a9e8-9717d9012fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa915bdb-7cd8-414c-815a-ac081c10d6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput</value>
      <webElementGuid>79d4a866-e2be-447f-a7b6-2fd1cd2f0594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dba7eb6a-4647-4438-beb6-1523788e1e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>637f8810-ccb5-4f70-9e69-b323a44b7241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>088a0a28-bc75-4659-a08a-6632073e9957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>092413ad-759e-4ab6-aa66-ca53772fe647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>8d3dfbf6-a817-43a0-bd67-77f088ce8da7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>2d8c93f2-19c4-42ab-9800-8c9ac0a208fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']/div/input</value>
      <webElementGuid>a8e71ce0-cf25-4f6c-8ef7-2d11a7ae4545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>f7ac5424-c3e0-4916-89e9-34213942ff52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>3b0030df-bc78-4963-99cc-962a141d6f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
