<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_PhotographicEquipment_Blanket_DropDown_PropertyType</name>
   <tag></tag>
   <elementGuidId>083a7532-669b-465e-8909-2d1323f54296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b1d329ac-3556-4c2a-bdab-b1ad3e6b5677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput</value>
      <webElementGuid>eac91b93-9ea0-4e26-84c8-6adb88959da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>429119b7-351e-412d-aaaa-8a26c06e6190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9a9d92a4-bbc7-465f-927f-5359f3bca023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Motion Picture ProducerAll Other Producer   </value>
      <webElementGuid>3abcd08f-794d-43fa-8023-f95d86190080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>99e299e6-b5a7-4afc-b6bd-06597d28e910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput']</value>
      <webElementGuid>4253fd26-1d70-463f-928e-3f135d5cba48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput']/div/div/select</value>
      <webElementGuid>6d4125a6-7214-4211-857f-5be4cba34a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Type'])[1]/following::select[1]</value>
      <webElementGuid>222f81e9-ec3f-4335-928a-2c63c64c4810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blanket Limit'])[1]/following::select[1]</value>
      <webElementGuid>95206bbb-16d6-483e-807d-80e7c8c34d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::select[1]</value>
      <webElementGuid>5e6df6c7-10d6-467e-b620-e9eae7920a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[2]/preceding::select[1]</value>
      <webElementGuid>3dfe94e4-bb30-48be-a12d-a83fc9540409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>4373e65d-bba6-4850-9ccd-f06794851b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-CoverageInputSet-1-CovTermInputSet-TypekeyTermInput' and (text() = '   &lt;none>Motion Picture ProducerAll Other Producer   ' or . = '   &lt;none>Motion Picture ProducerAll Other Producer   ')]</value>
      <webElementGuid>99090c5e-426e-4038-b481-349159a4a46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
