<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_IM7102_select_EmployeeTools_InstallationFloaterCov</name>
   <tag></tag>
   <elementGuidId>5788573d-6e98-4584-a9a7-67ca28617272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>547b4f88-de4f-4fae-91b6-a6bd05baddfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool</value>
      <webElementGuid>bfd95514-3075-44a3-9fd9-7af40da1ad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b76660e-7ca0-47c8-a2c5-4fa95391fe10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>14a1e5cd-e62a-4784-a9e5-cf61073fb7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>5c2fcb92-c69d-4f09-8ac6-42bf61e808a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>ad47e703-1d87-4611-a4b8-a31585adc9eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool']</value>
      <webElementGuid>a57cda68-95ef-4f9d-9fa0-4c01ad1e9a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool']/div/div/select</value>
      <webElementGuid>f7881996-1f54-4c76-bc1e-9cd6b90d18a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Tools'])[2]/following::select[1]</value>
      <webElementGuid>c750c8cc-e2e7-4462-9294-ccbf049d2f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Tools'])[1]/following::select[1]</value>
      <webElementGuid>06696397-d066-42c8-922f-d304d6480b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transportation'])[1]/preceding::select[1]</value>
      <webElementGuid>8b224eed-e74d-4b5d-bb1b-3902c50201cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount Shipped'])[1]/preceding::select[1]</value>
      <webElementGuid>5050d6f3-d75c-4f41-b8b1-976eace8f8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div[2]/div/div/div/select</value>
      <webElementGuid>7b417ccd-c0c4-4f87-9bd0-97bd3d4ae4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrtsEmpTool' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>9042fefa-1772-4bd0-904b-4090462c91ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
