<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_ElectronicDataProcessing_IM7203_Schedule_LocationInformation_Button_Ok</name>
   <tag></tag>
   <elementGuidId>a3d753ec-b43d-4765-a9b7-3aae353e4921</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='IM7LocationPopup-Update']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5c7cbad-acaa-475f-8fb7-3ce84540d012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5bcb3b4-53c3-4885-bf33-fe1b1ad7be1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-hasDivider gw-focus</value>
      <webElementGuid>5c06984a-d9e9-4326-8111-35743f839abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>386eba72-60da-4dcb-b912-a8ae136da877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ec56f02-528e-4c24-b87a-f5002672621e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:^</value>
      <webElementGuid>f6d646f6-30b0-4d60-8951-61aa06aebcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-shortcut</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;IM7LocationPopup-Update&quot;,&quot;key&quot;:&quot;U&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}</value>
      <webElementGuid>3f3bdabc-6840-453d-a1e9-57fded2a7193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1070135f-0a12-473d-9330-5875cf18cc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OKOK</value>
      <webElementGuid>859edd41-bc0d-4cb1-b0aa-53db626f15b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7LocationPopup-Update&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]</value>
      <webElementGuid>f3160306-bcc0-40bb-927a-359234242fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7LocationPopup-Update']/div</value>
      <webElementGuid>aebfd013-63da-445e-a183-391070b2579a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to Electronic Data Processing'])[1]/following::div[3]</value>
      <webElementGuid>262ebe59-317a-4bbb-98c2-438cf68df3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Information'])[1]/following::div[5]</value>
      <webElementGuid>6bfcfc3e-83d1-4ae3-91d3-340d67048cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[3]/div[2]/div/div</value>
      <webElementGuid>4224a52d-5ed1-49d4-8041-26a8edf58c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OKOK' or . = 'OKOK')]</value>
      <webElementGuid>a13ebef0-09d8-4651-87d5-25101d6bed6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
