<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_IM7102_Select_DeductibleType_InstallationFloaterCov</name>
   <tag></tag>
   <elementGuidId>9f5c9e3c-998c-4569-b57b-020ff013f241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4058144b-7149-4f9b-868c-7ac3369a883a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc</value>
      <webElementGuid>e22a3260-4635-407f-9004-b308212b89ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>579e82d8-d63e-4f17-8574-a66b096c10b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>986b9242-3643-4e05-af70-735c1b55e7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   Single DeductibleMultiple Deductibles   </value>
      <webElementGuid>0985fee0-08dd-45c6-9bd3-7069042f7f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>4a51bc5a-9cf8-4902-ab71-e963cd6bc8cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc']</value>
      <webElementGuid>2f803d8c-78f8-4415-a2ef-5e972d0d1bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc']/div/div/select</value>
      <webElementGuid>015a913d-21aa-4381-908b-0cd2d77742ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible Type'])[1]/following::select[1]</value>
      <webElementGuid>16ed6b9e-64fa-42ac-b9aa-4c7d61794381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catastrophe Limit'])[1]/following::select[1]</value>
      <webElementGuid>e1c3aae5-22b0-46f0-8335-ec8cbb6873f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/preceding::select[1]</value>
      <webElementGuid>87ae1f12-b14a-4965-b6b4-8164a7ccd4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installation Receipts'])[1]/preceding::select[2]</value>
      <webElementGuid>b9d85735-213c-4d1f-8822-fd90c4edd058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8e26bd1b-8e83-4ffc-b7b3-1141fa006cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsDeduc' and (text() = '   Single DeductibleMultiple Deductibles   ' or . = '   Single DeductibleMultiple Deductibles   ')]</value>
      <webElementGuid>2ba18b84-7393-4158-b019-418444326b51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
