<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MotorTruckCargo_PartLevelInfo_PropertyInVehicleLimit</name>
   <tag></tag>
   <elementGuidId>eb726574-4b23-454e-9b3c-2def7d6440b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e668f2a-1a95-4acd-bb37-ac8eba2d08b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>156aa503-f1a5-4d02-9492-26d8a813e930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit</value>
      <webElementGuid>f2703118-c8a8-400e-a120-23bd5e8a6306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ae16911c-18c4-437b-b825-d2fec57567d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>425d041f-a923-4b8a-bb33-19d8a23f7d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>bfff2fae-6b48-4d64-b6a7-9261a3878b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>047b917e-3e3d-48ce-ba96-ef3de921ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>64c81b84-d4ca-4bbc-b063-cbd7fd954c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit']</value>
      <webElementGuid>4a34b314-df00-4815-bd0b-6c421cec6c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit']/div/input</value>
      <webElementGuid>05503c5a-e62a-486a-82c3-2289d53c01f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>beb2f544-d243-4881-8e22-ed8a5574bcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCPropInVehicleLimit']</value>
      <webElementGuid>cdf0d5b3-9412-4110-b44e-c6605f9369b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
