<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_REGE_CoverageSchedule_Textbox_CoveredEquipment</name>
   <tag></tag>
   <elementGuidId>b135074e-2f1f-43ce-b16d-4403df369e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name='IM7RenwablEnrgyGentngEquiPopup-IM7RenwablEnrgyGentngEquiPanelSet-ScheduleInputSet-0-coveredEquiCell']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
