<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_BuildersRisk_IM7980_ScheduleCalenderButton_JobCommencement</name>
   <tag></tag>
   <elementGuidId>7d5947a7-7512-45cb-8fa5-f8e937a4a7ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36ab6083-95dc-4624-a441-a4a4787714c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon</value>
      <webElementGuid>d7317322-0b89-44fa-a619-6053e51b5bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da8c8baa-5b1e-40f3-add2-c32290289abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-min-visible gw-date-icon gw-focus gw-inDatePicker</value>
      <webElementGuid>b1c609cb-b4e6-4120-b029-155ffb7de6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f56b9ff-48c8-4a38-81fb-7556c4cb090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>2789e010-e734-4841-b127-11ee713f75d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ffe456b1-c492-4006-b039-437c0b73b0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>gwDateValue.dateIconClicked id:IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement</value>
      <webElementGuid>3116aec1-8200-48cb-8b7e-e3b79be06976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>toggle date picker</value>
      <webElementGuid>93244ec9-2baa-4eae-823f-7b4c93ce142c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0ec591f3-9ec1-4364-8d97-51d62f080f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon&quot;)</value>
      <webElementGuid>1a2e6939-298b-41d1-a4b4-e7720bbfa5e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon']</value>
      <webElementGuid>48be64a0-7321-401b-bb1b-87fd04dd0c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement']/div/div</value>
      <webElementGuid>e8e30050-d2ae-4def-b424-6e3e3cf8c741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobsite Security Description'])[4]/following::div[34]</value>
      <webElementGuid>96f41cae-81b8-4a99-8740-65f30bb24927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobsite Security Description'])[3]/following::div[41]</value>
      <webElementGuid>6ddf3e6d-deca-4fd4-98bd-07db4c672245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::div[11]</value>
      <webElementGuid>daea601f-cd3c-4001-85d9-8fef776a0f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='M'])[1]/preceding::div[12]</value>
      <webElementGuid>83a7d1f9-1b98-4a62-9a44-8f663a43dced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/div/div/div/div</value>
      <webElementGuid>27df65bf-f1bf-4e88-967c-fca6e083cb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-JobCommencement_dateIcon']</value>
      <webElementGuid>66e44666-653b-4334-93dc-36b7dfb54c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
