<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_FineArtFloater_IM7401_ScheduleonFile_SpecialPerilsLoad</name>
   <tag></tag>
   <elementGuidId>40a73f28-88ee-47fc-a14f-2c6467a63286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82cc124c-3cb3-4d40-b966-880123690e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0f009cd-cec7-4b3b-aff4-7775903110bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile</value>
      <webElementGuid>a1cb6281-8345-40c1-9243-b6247a1f8ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c8c330fb-a7b8-4bf4-86ed-f10f7dfe4ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>81bee060-414e-4b7c-a096-ffc0238db9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>6245c7a3-f9d8-4103-a9fc-e0fcfd3a89f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4ca29dd2-3e4e-4528-888b-adc6ef8e1153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>1eec3fc4-ba31-4863-9840-fab08249b3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile']</value>
      <webElementGuid>f092286f-8b4c-48b1-9afd-725a808b04aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile']/div/input</value>
      <webElementGuid>f45300b0-02e3-468e-8714-bcea0a8ce13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>280d5a69-38a2-4558-9280-086e7339e222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-CovTermInputSet-IM7FAFSchedSpecialPerilsLoadFile']</value>
      <webElementGuid>6df0e3c7-babc-4a4b-ac23-d93662708aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
