<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_FineArtsFloater_Checkbox_IM 7400 Fine Arts Coverage_FineArtfloater</name>
   <tag></tag>
   <elementGuidId>d0e9f177-0f9c-4cb7-a801-0a9d6381cf82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e35583fb-8e2b-4db3-835a-06bc65773b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>88b3f546-b466-4259-80e7-c8318611846f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5d08f869-d6b1-4b22-a37a-2cc616de2200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>IM 7400 Fine Arts Coverage - Fine Art Floater visibility toggle</value>
      <webElementGuid>86f8cda6-ddac-4172-a324-f863c0bbe927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9937470a-7f4b-463b-a43c-8d66ffecce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>52b07160-a4e2-467e-8c6b-5a9c66301932</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>9ebdc046-fb7f-4c8e-be97-aa67ce65921d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>bd20e15b-56d1-4376-9ce3-d44b9e190481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b7114c7d-f749-46f1-ad37-e96b3c6db763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>30d71234-32d4-466c-9bfa-7970a6508fd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
