<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_InstallationFloater_IM7127_TextBox_SparePartsFuelAndLubricantsLimit</name>
   <tag></tag>
   <elementGuidId>c2aea0d5-d29f-4de8-b3b0-20cdba91bebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>607f6c40-e146-4371-9c03-6e969b95b893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>062220e2-bd77-4737-8047-f3f59dd874ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt</value>
      <webElementGuid>8aeb086e-c3b6-4c70-b5f5-ad5b006f6273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3eb6b869-306b-4329-8fb0-ef8540c049a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d4cc75c9-e02d-4264-80c9-03bec42a89d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>9ea447b7-0ee7-4056-a380-63c256c01baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>eb597a07-7e2c-4862-b6cc-90affedd046c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>88ba7946-dbc4-432c-af54-45893de40faf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt']</value>
      <webElementGuid>16095f1d-9b98-4fce-8105-ff6ceb5e0c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt']/div/input</value>
      <webElementGuid>90aaa347-aa04-4019-b704-c2472108ebce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/input</value>
      <webElementGuid>dbeb0af4-7bb1-4067-a7fd-b7bad9b77032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovSparePFALYLmt']</value>
      <webElementGuid>9304cf44-96b5-43fc-b5cb-d3cdd6418aef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
