<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_Transit_Select_Commodity</name>
   <tag></tag>
   <elementGuidId>6ff128b1-d4d9-40db-8c71-64fac1f33753</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCommodty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCommodty&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6f55e32f-498c-4e01-8898-f051d0071405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7TransitPopup-IM7TransitPanelSet-TransitCommodty</value>
      <webElementGuid>df59d4b9-af11-482c-a178-d7cc67a2236a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b8eec797-3e7c-41f3-b76b-d03c7ad6676d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>743e578c-3a64-43c6-9f47-2a6b27c1941b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Agricultural equipmentAlcoholic beverages (except beer and wine)Appliances (except TV and stereos)Automobile parts and accessoriesBeer and wineBeverages (nonalcoholic)Building materialsCameras and filmCanned goodsCement, sand, or gravelChina and ceramicsCigarettes and cigarsClothingClothing - Ladies' and men's dress apparelComputersContractors' heavy equipmentCosmetics and perfumeDangerous articles, explosives, corrosives, flammables, acidsDairy productsDrugs (except narcotics)Dry goodsEggs (shell)Electrical supplies and fixturesFarm productsFertilizerFine artsFood productsFood products - Frozen or refrigeratedFood products - Meat or seafoodFurnitureFursGeneral merchandiseGlasswareGrain, hay, feedHardware and paintHousehold effectsJewelryLeather goods (except shoes)Livestock and live poultryLiquid haulers (bulk nonflammable)LumberMachinery and heavy equipmentMachinery and heavy equipment - Specialized heavy haulersMachinery and heavy equipment - Power toolsMetal and steelNarcoticsOffice equipmentPaper and paper productsPetroleum productsPetroleum products - Under 140 degrees flashpointPipe, cable, and wirePlumbing suppliesPoultry (dressed)Precious metalsRugs and carpetsRugs and carpets - OrientalShoesSporting goods and toysTextilesTires and tubesTV, radios, and stereo equipmentVideo equipment and tapes   </value>
      <webElementGuid>cece1175-0b5d-45ee-bfe9-ab93095cf71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCommodty&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>2c709361-e035-4836-bb29-946fc3e746dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCommodty']</value>
      <webElementGuid>3ca32632-5434-43fc-a2c2-19af694f264f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7TransitPopup-IM7TransitPanelSet-TransitCommodty']/div/div/select</value>
      <webElementGuid>4468c9e1-ff78-41f3-be18-aeca16579a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commodity'])[1]/following::select[1]</value>
      <webElementGuid>c23fabb4-98b4-4a46-a9ef-5c58d6df0932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Part Level Information'])[1]/following::select[1]</value>
      <webElementGuid>ec95f430-f6b4-4c13-871b-83ec0c30bccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classification'])[1]/preceding::select[1]</value>
      <webElementGuid>105d3667-11b7-498c-86e3-dbd55c1d8050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transit Coverages'])[1]/preceding::select[1]</value>
      <webElementGuid>db3d094f-0292-424f-b8f2-77e8dfa46252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6df3bfc9-d45f-4bb3-811d-77c46a4e6e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7TransitPopup-IM7TransitPanelSet-TransitCommodty' and (text() = concat(&quot;   &lt;none>Agricultural equipmentAlcoholic beverages (except beer and wine)Appliances (except TV and stereos)Automobile parts and accessoriesBeer and wineBeverages (nonalcoholic)Building materialsCameras and filmCanned goodsCement, sand, or gravelChina and ceramicsCigarettes and cigarsClothingClothing - Ladies&quot; , &quot;'&quot; , &quot; and men&quot; , &quot;'&quot; , &quot;s dress apparelComputersContractors&quot; , &quot;'&quot; , &quot; heavy equipmentCosmetics and perfumeDangerous articles, explosives, corrosives, flammables, acidsDairy productsDrugs (except narcotics)Dry goodsEggs (shell)Electrical supplies and fixturesFarm productsFertilizerFine artsFood productsFood products - Frozen or refrigeratedFood products - Meat or seafoodFurnitureFursGeneral merchandiseGlasswareGrain, hay, feedHardware and paintHousehold effectsJewelryLeather goods (except shoes)Livestock and live poultryLiquid haulers (bulk nonflammable)LumberMachinery and heavy equipmentMachinery and heavy equipment - Specialized heavy haulersMachinery and heavy equipment - Power toolsMetal and steelNarcoticsOffice equipmentPaper and paper productsPetroleum productsPetroleum products - Under 140 degrees flashpointPipe, cable, and wirePlumbing suppliesPoultry (dressed)Precious metalsRugs and carpetsRugs and carpets - OrientalShoesSporting goods and toysTextilesTires and tubesTV, radios, and stereo equipmentVideo equipment and tapes   &quot;) or . = concat(&quot;   &lt;none>Agricultural equipmentAlcoholic beverages (except beer and wine)Appliances (except TV and stereos)Automobile parts and accessoriesBeer and wineBeverages (nonalcoholic)Building materialsCameras and filmCanned goodsCement, sand, or gravelChina and ceramicsCigarettes and cigarsClothingClothing - Ladies&quot; , &quot;'&quot; , &quot; and men&quot; , &quot;'&quot; , &quot;s dress apparelComputersContractors&quot; , &quot;'&quot; , &quot; heavy equipmentCosmetics and perfumeDangerous articles, explosives, corrosives, flammables, acidsDairy productsDrugs (except narcotics)Dry goodsEggs (shell)Electrical supplies and fixturesFarm productsFertilizerFine artsFood productsFood products - Frozen or refrigeratedFood products - Meat or seafoodFurnitureFursGeneral merchandiseGlasswareGrain, hay, feedHardware and paintHousehold effectsJewelryLeather goods (except shoes)Livestock and live poultryLiquid haulers (bulk nonflammable)LumberMachinery and heavy equipmentMachinery and heavy equipment - Specialized heavy haulersMachinery and heavy equipment - Power toolsMetal and steelNarcoticsOffice equipmentPaper and paper productsPetroleum productsPetroleum products - Under 140 degrees flashpointPipe, cable, and wirePlumbing suppliesPoultry (dressed)Precious metalsRugs and carpetsRugs and carpets - OrientalShoesSporting goods and toysTextilesTires and tubesTV, radios, and stereo equipmentVideo equipment and tapes   &quot;))]</value>
      <webElementGuid>90f6c18a-fc27-47be-8c87-ea28dec82629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
