<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MotorTruckCargo_VehicleInformation_Model</name>
   <tag></tag>
   <elementGuidId>2b53c986-d311-40ca-904c-ce8994140221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bdbc7c5b-5517-44f2-a8ce-040f89111600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13805ffd-9161-4809-8f6b-fab24bc946f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell</value>
      <webElementGuid>35269947-7cab-4fa5-a362-5454809cac40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a11aff2c-bff5-40b1-bfef-abfbe8928357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9fd63392-8d71-40a7-bf47-39737005d517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>30b77ece-0d3f-4d03-99bb-c0108b4ccb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>ec1e8725-456f-4d7a-b316-e1af5f3ff2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>4ec1eabb-c1d7-4dbc-b7f4-ee9b2697db46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell']</value>
      <webElementGuid>8f5bb81e-6a03-40f7-8ab1-430b3a19714d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell']/div/input</value>
      <webElementGuid>d0dcc394-02b8-4f8a-b45b-cad47f45f267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/input</value>
      <webElementGuid>ffa9ce38-2da5-4aab-a8c4-02a4910ac28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7MotorTruckCargoPopup-IM7MotorTruckCargoPanelSet-MTCVehicleSchedCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-ScheduleInputSet-0-modelCell']</value>
      <webElementGuid>3683d95b-3ece-4389-a428-e20fb1cb354e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
