<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_InstallationFloater_IM7127_TextBox_ContinuingRentalOrLeasePaymentsLimit</name>
   <tag></tag>
   <elementGuidId>eee3a5ff-9b5b-4374-8d58-6557b9fad44e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eef4b311-bb2c-4e1b-9fd7-d738cbb1256f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ff99ac65-9a6a-4400-9f3c-f89f7bd38b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt</value>
      <webElementGuid>65c10c47-6215-4896-85bd-150c2d86e770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0baaa87-452a-4945-af00-3a311a9124ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>95f01cd8-9ed6-4ec6-8bc2-e6ee82d6767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>d6a48277-bcda-4075-bcb4-da8c1f59bce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3d021bd5-4aef-40c2-949e-36bed87f96c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>4c1f207f-6f01-4e3e-8827-4345fe39792d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt']</value>
      <webElementGuid>e974e0c2-c938-4ee1-a2bb-aef93b1ff019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt']/div/input</value>
      <webElementGuid>96b2533c-0f72-46c8-8717-7c2150a113a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>0af619f1-fa8c-434a-98ec-adfb99d8cd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovContRLPYLmt']</value>
      <webElementGuid>8ba1c295-c305-4e91-b193-c5cefd4aa918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
