<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_PhotographicEquipment_Blanket_TextBox_Rank</name>
   <tag></tag>
   <elementGuidId>ddd83ff9-a896-41ea-be7b-3825dddbb267</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51d81746-51e4-4593-922c-8dc726e5fbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3055011d-38d3-4633-85ea-e9f88a1d64f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank</value>
      <webElementGuid>1693479e-5756-465a-9b9b-31e24bb641c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a35303f-fd77-4da2-b93c-482e6b9003cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a1f9ad0c-9f68-4565-a049-9a5ea0c2e3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>b684dc9b-9edc-42ff-9237-490e1c861d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>e0ab0a07-f093-4ce3-a83f-e116e2f0b241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>643d9d8f-085a-4368-8d97-d9e375cf4798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank']</value>
      <webElementGuid>184f4ca8-0f9c-43ff-a614-d1b4c78101df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank']/div/input</value>
      <webElementGuid>900fa86e-b012-4d50-9224-50f61d87c13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/input</value>
      <webElementGuid>9fd97af8-7e08-4b1a-bdde-c3a110a2164d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7PhyNDentEquipAdditionalInterestDV-IM7AdditionalInterestLV-0-Rank']</value>
      <webElementGuid>2f33c039-c8d0-436a-9bcb-1f17b6831212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
