<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_AccountsReceivable_Coverage_Schedule_SectionOfBuilding</name>
   <tag></tag>
   <elementGuidId>d0c2b3f8-d5bb-4a68-b068-11241fcc9de8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8320868b-0084-4147-a416-bfc377f99e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56ee45aa-bbdd-4971-ab08-9fef07abbf93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding</value>
      <webElementGuid>f2e43c9a-9d8a-41f9-8b8d-7903229ca116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>40bba803-9cbc-4ccf-b60e-e6caae44b74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f26f5aec-792f-419d-b9c3-98fbb0e39a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9ee9add6-c8a6-4e82-8ef8-e3ca7443551f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>90306b6a-c0be-4c54-bd0d-9895620097ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>dbfab430-cf3e-4d9a-8a8a-e9874c5e4142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>a2c20e1a-ce24-4195-847c-a43e631ab0e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding']</value>
      <webElementGuid>12b86ed5-cc5a-4d6c-9c25-1f96a93e7244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding']/div/input</value>
      <webElementGuid>95b54380-f79a-4f2c-92ab-c54620f68e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div/input</value>
      <webElementGuid>9547661f-1fb6-47b7-ba50-66c0dfe928f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-ScheduleInputSet-0-sectionOfBuilding']</value>
      <webElementGuid>8bc5861b-8e79-4c20-9e85-5ffef8097503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
