<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_IM7102_input_InstallationReceipts_InstallationFloaterCov</name>
   <tag></tag>
   <elementGuidId>1f594a48-cab4-45e1-80cf-28bd1783db45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6943363f-9944-4d1d-9172-537dcb4a0bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1acef2c2-a440-4a62-9564-717fd21a9a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts</value>
      <webElementGuid>989ba9ba-71c9-4654-8c91-5c3a0ac09bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a15684e4-51b5-41a4-babc-ed84dbe33054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>086e81e6-dbeb-4ae0-ab31-c5872914781b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>0a783ec0-2227-4d6f-8ecd-e596a0714660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>a60e4e10-ecaf-4eba-ba6f-67897531d2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>19ebcc9b-7ab7-4000-8ad6-9baa47dad584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts']</value>
      <webElementGuid>14d80b78-cf42-465b-ae74-b26e1dadd3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts']/div/input</value>
      <webElementGuid>1603fff3-e2fa-476a-b78c-a112faed80fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>c1040fda-c142-488e-8d73-fe9f1a67a0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-IM7IFCovContractorsIFCovContrctsInstallationReceipts']</value>
      <webElementGuid>fce26160-18ea-4fe3-981e-29dbed457032</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
