<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_PhotographicEquipment_ScheduleCoverage_DropDown_OwnLease</name>
   <tag></tag>
   <elementGuidId>981af0a7-bbab-4dcd-bf8a-056f048046f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0dc0b75b-2f9d-475b-8f83-a3009084aa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease</value>
      <webElementGuid>8295e015-6ae7-421b-a354-15084f008ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa786908-d503-4a7c-9724-3bbe1ea777bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>2b2bbc69-c1c9-4b82-9db9-d83f8c5e7b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>OwnedLeased   </value>
      <webElementGuid>ce6206a1-77bf-43a6-b504-79154600ec78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>0e55b9df-a7cc-4be3-90a5-8d7318689d6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease']</value>
      <webElementGuid>324fc62c-9723-4135-927f-8810b7265dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease']/div/div/select</value>
      <webElementGuid>e4a3fbed-49da-4627-a0d0-9b2dc0daa223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[2]/following::select[2]</value>
      <webElementGuid>bb52018b-3df5-4d9e-a9dc-26a2ba566d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[1]/following::select[2]</value>
      <webElementGuid>6260d107-dfcb-4994-91c9-6466c84b4c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::select[2]</value>
      <webElementGuid>1446c47b-629b-4163-aac5-835626258aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ad'])[3]/preceding::select[2]</value>
      <webElementGuid>703a5a0a-6c2d-4ec5-a69a-96589f57fe2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/div/select</value>
      <webElementGuid>b0e0ae0d-920f-4490-86d4-8e687c61b0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-Ownorlease' and (text() = '   &lt;none>OwnedLeased   ' or . = '   &lt;none>OwnedLeased   ')]</value>
      <webElementGuid>ba6259fd-ae6c-4cc0-83d7-8e0cf4f981a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
