<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_IM7611_Schedule_Dropdown_RestorationPeriod</name>
   <tag></tag>
   <elementGuidId>587ad94b-67a1-4807-b63f-86baf54b48b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[5]//select</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
