<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_FineArtsFloater_TextBox_AnyOnePieceOfArtLimit</name>
   <tag></tag>
   <elementGuidId>81700cad-dfc0-4194-84ff-76125356456c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f01587bf-f56c-4536-b2b5-6395ce0ebefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57c095fa-7329-42a8-b013-56d47843ae0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput</value>
      <webElementGuid>72f7d320-d44d-4b21-9074-ec20fba2e545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3496bf9c-ac2c-4adf-8a8e-62461590874c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7a1c1e1f-2651-40bd-8e1c-506470358bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>283f44d7-7c06-483c-a678-0b13c1a895b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>d4af5c14-88f8-493f-962d-a042757835c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>4f616d91-8f2a-4bc0-bb23-524d56522914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>5c2db8a8-ad01-4c04-8a9a-ca8473c8fdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']/div/input</value>
      <webElementGuid>2c77c1f9-91d0-447b-85aa-15ff2b7f579c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>9c244e9a-aee8-4f6d-ad7f-a510d589b7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-FAFCovCovPatterns-CoverageCategoryInputSet-2-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-CovTermDirectInputSet-DirectTermInput']</value>
      <webElementGuid>04cff2d2-76af-408f-bbfd-d684e4ff6984</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
