<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_BuildersRisk_IM7980_ScheduleTextBox_OwnerSuppliedPropertyAmount</name>
   <tag></tag>
   <elementGuidId>a1bd8ba3-195f-49ee-8662-158d48b2fccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abee26d1-f92f-4b13-a66a-f3456a14cbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0959cdd-fdaf-49cf-b58c-6970e7ef3572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied</value>
      <webElementGuid>d7c4f6e8-4497-42df-8265-f4a4d1f9798d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a82fb67b-8600-4fc9-a300-b9a4fd1bcc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2473c597-d744-4bbc-aac1-7231387f2a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>87ecc197-1bdd-4ea6-91b7-5d01f552d8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>0d7d69f3-28f3-40b9-9280-09df5096ef36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>7d95e688-7025-42f8-bde4-894e7fe49826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied']</value>
      <webElementGuid>3351869e-d1bc-4b67-942a-05b4f90688da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied']/div/input</value>
      <webElementGuid>b54fc62b-54e7-4a0e-ac1e-4ebe97546119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/div/div/div/input</value>
      <webElementGuid>d79f96c1-1982-4d5f-ab9c-d4c036e7b882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7BuildersRiskPopup-IM7BuildersRiskPanelSet-BRClauseCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-OwnerSupplied']</value>
      <webElementGuid>bf572b3c-7fa3-452d-862a-fa1343e2c840</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
