<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellaneousForms_IM7316_Schedule_IncludeLegalLiablity_ProcessingCoverage</name>
   <tag></tag>
   <elementGuidId>f6f265b9-1208-481e-891a-b960485def0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>105ee7bf-7a67-416e-b57d-3bcd50495728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell</value>
      <webElementGuid>7b3bdd64-b245-4464-ba7e-cb2d8ed67619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4128e23f-88c2-440a-a32d-6a571d8e1020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>6356a777-6a1b-4aac-9440-23c510846d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>bfd92e92-828d-4c15-beb5-48df6a9601e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>18dce65d-2264-477b-8bd0-f96e6316c1be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell']</value>
      <webElementGuid>8da7e8e4-589b-4a23-9575-559aae56c0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell']/div/div/select</value>
      <webElementGuid>254a40bf-a477-4d62-890f-d60744335e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing Coverage - Any One loss Limit'])[2]/following::select[3]</value>
      <webElementGuid>88e0a3df-18c0-4a8f-9b5f-88bbb2424eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processing Coverage - Any One loss Limit'])[1]/following::select[3]</value>
      <webElementGuid>fec9ca25-5d04-44bd-890d-3cad52fe1e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IM 7341 Drone Coverage Form'])[1]/preceding::select[1]</value>
      <webElementGuid>428ff39a-ebe7-48c0-b75c-800250a05d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IM 7341 Drone Coverage Form'])[2]/preceding::select[1]</value>
      <webElementGuid>50bc64e0-88d0-497e-845b-ac9394d7b084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/div/div/div/select</value>
      <webElementGuid>b77fcdfb-51ca-43d1-a6b5-6d35679cf456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-4-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-processingCoverageCell' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>da9803a5-f5ae-41f7-8be0-a79747f3fcd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
