<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_InstallationFloater_IM7100_JobDescription</name>
   <tag></tag>
   <elementGuidId>3a5dc6dc-e4d3-4228-b8db-50a80cadbbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>28f0a74d-4f4c-47ba-921a-543e408a4795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c08f7686-e561-474d-9068-383eaa4cd360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription</value>
      <webElementGuid>f8a3252e-46fa-42ef-b618-1e53ceb7ad95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>0dd36742-4e04-420f-be58-f7a77798db60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>6a846438-db3b-4e5b-acd8-1c8d9d454ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription&quot;)/div[@class=&quot;gw-vw--value&quot;]/textarea[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>5c6427fa-d8f4-49d3-8409-b56a119dc292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription']</value>
      <webElementGuid>e4fea5d2-7d2d-485a-b994-3763be6192d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription']/div/textarea</value>
      <webElementGuid>79d64b59-1c25-488a-877f-7468e3de1a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>549b4023-3916-40d7-b640-96d051cd55ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-IFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-JobDescription']</value>
      <webElementGuid>ffb2b3bb-f14f-49cd-9ed9-c1189478b892</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
