<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_Signs_Textbox_CatastropheLimit</name>
   <tag></tag>
   <elementGuidId>747dc6ca-6467-45fe-8eaf-23011c4f996e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cc8ac55-3d2d-4002-ad57-21f12277fa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7a98867-09b7-440f-b9dc-11dfbb1ef817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit</value>
      <webElementGuid>530ac394-6876-4c5b-8b5c-3624123148ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ced7ae79-104c-4fce-b526-bd465f2a8991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>de36dbc9-dac0-4572-a885-e87ba778e9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>0e485661-d10d-431c-b559-8c6591d4ac01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>595f850c-0187-4eb5-bdc9-483c2e0c77b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>ef08b14d-519c-4823-80f2-a12fe74c07c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit']</value>
      <webElementGuid>765ba8a6-aee2-47dc-a8c1-fd550f8e66a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit']/div/input</value>
      <webElementGuid>455f50ee-1311-4b1a-903e-070f15d20d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>94deeadd-4e48-4548-872d-52c05f1d7f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7SignsPopup-IM7SignsPanelSet-SignsCatasLimit']</value>
      <webElementGuid>b817e6e0-2958-4c06-852b-bc4edb64b067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
