<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_AccountsReceivable_Select_PropertyAtPremises_CheckBox</name>
   <tag></tag>
   <elementGuidId>94ac6ac8-5d2b-438a-886c-b9bf7c751d43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>c</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ebd8b63-bd3c-45af-8f1a-06561dd6dddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>b6b7fbed-1014-49b0-af48-ea6abca191f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>89053281-59ae-4367-86fc-44409ad55443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Accounts Receivable - Property at Premises Not Described on Schedule of Coverage visibility toggle</value>
      <webElementGuid>0e7485b0-c160-4243-a663-ae490cc80832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>403212ed-ee25-4f6a-965f-40ce3c500862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>7b193038-4451-4a41-8f3b-5ba8a3abcb28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>eb4fefaa-6aef-4811-9300-f663363876e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>3ad19f1b-7e62-41d5-8c5e-8da2578360c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>882ee20c-4ad5-41ed-a81a-1c2d3ad513d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'IM7AccountsReceivablePopup-IM7AccountsReceivablePanelSet-AROffPremisesCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>9f9e9e17-4f4f-4b74-92ed-68c47e338287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
