<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_FineArtsFloater_AddCov_IM7419_DropDown_Deductible</name>
   <tag></tag>
   <elementGuidId>b55bae7a-9b37-492f-b7d6-5cdff0dff504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>530a02f9-96c7-40fe-ae50-76373a54ab16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput</value>
      <webElementGuid>6bbb6cd7-36ac-4704-9ca3-5130b48cda43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ecd6fec-2c79-49ee-b29d-4fc95b900456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>adbda861-20b5-4ea0-a0b8-2d030c3c98f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   2505001,0002,5005,00010,000   </value>
      <webElementGuid>77475393-3378-4b6d-8825-7170c1ceab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>7631000b-7400-44b3-8372-ffe0ebc6ff99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput']</value>
      <webElementGuid>c53f894e-f4b3-48a5-a33d-c750cddf1494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput']/div/div/select</value>
      <webElementGuid>bf078484-ceba-4b92-b24c-5a775adfe745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[1]</value>
      <webElementGuid>fcc83c8f-f3f2-4024-900e-a2d444265cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[1]/following::select[1]</value>
      <webElementGuid>8c76a3d1-cf6c-4cc8-bd32-13b4fe55ad1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c843fd3d-52f0-4541-b771-1315fc8ffd93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7FineArtFloaterPopup-IM7FineArtFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-TypekeyTermInput' and (text() = '   2505001,0002,5005,00010,000   ' or . = '   2505001,0002,5005,00010,000   ')]</value>
      <webElementGuid>e1797ad6-9d54-44cd-9be4-fcce95eead7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
