<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_PhotographicEquipment_ScheduleCoverage_TextBox_Limit</name>
   <tag></tag>
   <elementGuidId>e00daa97-18ac-4edd-b529-d4b9bb94c75e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f136642-ab41-457f-af7c-aa7cf6ac3f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7a5e3a2-492c-4262-a1a8-8c4eb014784b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell</value>
      <webElementGuid>3a41d31a-eb1e-4900-b1fc-9d89b9960506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08394e1a-db41-4e44-8353-220af55741de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>8cf5d774-c192-437d-9919-dbf43b716c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>67d05909-4905-40a9-a89f-f4d04c61ba91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>fd928ce6-35ac-49ab-bb16-90eb6dccabe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>626c1573-11bc-4905-8a9b-fb80f8752095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell']</value>
      <webElementGuid>4f433940-7c0a-4757-a9b5-9e7152b89a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell']/div/input</value>
      <webElementGuid>73099e7f-27aa-4bbf-ac25-719d510edf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/div/input</value>
      <webElementGuid>27a931d0-1c89-4239-a78e-e89c7f2b20d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7PhotoEquipPopup-IM7PhotoEquipPanelSet-IM7CoveragesCategoryPanelSet-0-IM7CoveragePanelSet-ScheduleInputSet-0-LimitCell']</value>
      <webElementGuid>f80a33e1-f7ec-4051-8da8-6245e980da78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
