<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellaneousFloater_IM7500_Schedule_BasicLoad</name>
   <tag></tag>
   <elementGuidId>149829d5-a2af-49b8-98f8-224412c2fc75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>299c2095-cc72-4e89-a0e0-a9ddf1ba6c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdc683a6-0a20-41a4-aeb5-a888fa3a962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad</value>
      <webElementGuid>12ff6684-fd11-4cfd-a384-12433af7c75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90e4eb3c-871a-4b64-854c-25d14d9f9331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>9894079f-6a6d-4a0c-bf68-0cffa481137f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>bb2b77b2-bb44-48e1-b25f-a0924212c48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4e9cec4f-7553-438d-a347-24e305526007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>44038601-802d-43c2-aae0-971161ceb1f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad']</value>
      <webElementGuid>4bc441cf-abd2-445a-a899-b4714519bb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad']/div/input</value>
      <webElementGuid>b43eef50-dacd-46f9-a7c6-4afe5135300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div/div/div/input</value>
      <webElementGuid>2d13c647-22ad-47a8-b0d6-a837f830987e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-0-CoverageInputSet-CovPatternInputGroup-ScheduleInputSet-0-BasicLoad']</value>
      <webElementGuid>1e7d8a38-f658-4142-8c5a-5f4448b262d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
