<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellameousForms_IM7341_DroneCargoCoverage</name>
   <tag></tag>
   <elementGuidId>3f89fccc-49ad-4418-979e-35d180155115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b931023d-3977-4f5a-abe9-84fd27682bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo</value>
      <webElementGuid>723eff33-e28b-47af-bba5-96dcdbc2d635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f5549c6-06dc-4884-9c6a-7387594eb6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9d7b1e6c-7105-4329-b5a2-cd75f81c3bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Coverage Not ProvidedDrone Cargo Coverage   </value>
      <webElementGuid>cd17f531-7afa-4639-8d92-36a86287d1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>f859157b-02e5-499e-8773-dc3eeddd98e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo']</value>
      <webElementGuid>bf671f71-1483-45c2-ae11-16bc7713ef8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo']/div/div/select</value>
      <webElementGuid>3de9779e-081b-45d2-bf64-e72a91f89cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone Cargo Coverage'])[1]/following::select[1]</value>
      <webElementGuid>5d038e7c-c4a6-4631-8567-c6f1a7860ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drone and Ground Equipment Coverage Valuation'])[1]/following::select[2]</value>
      <webElementGuid>161158e8-3249-42fd-8021-8d86aae9c48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Electrical Disturbance'])[1]/preceding::select[1]</value>
      <webElementGuid>854ad98a-c994-4cab-96fe-ba5f4f4b4dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/div/div/select</value>
      <webElementGuid>d1fd791f-2d44-415a-b69b-222f2d708146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7MiscellaneousFormsPopup-IM7MiscellaneousFormsPanelSet-MiscFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-IM7MiscFDroneCovMiscFDroneCargo' and (text() = '   &lt;none>Coverage Not ProvidedDrone Cargo Coverage   ' or . = '   &lt;none>Coverage Not ProvidedDrone Cargo Coverage   ')]</value>
      <webElementGuid>e475da62-1027-457d-b92d-563abcaa6fd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
