<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_InstallationFloater_IM7127_Dropdown_EquipmentHauling</name>
   <tag></tag>
   <elementGuidId>233e6bc6-8cc8-499d-8957-27b3fcf544c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5425b71e-fed6-478d-aee6-928b493069bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln</value>
      <webElementGuid>7aa2ad5d-2557-468d-962d-65a0402a0f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d293c93d-c39b-4bbf-8419-e9743fa39f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>cc903c6a-fa72-4979-bb31-d3ba8b1212a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>e5272ed2-6a5f-4b71-8a12-4c27d1815bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>5c2854c5-7e4e-47a9-aa57-22400edd2f76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln']</value>
      <webElementGuid>f1bf6551-92b4-465b-a75b-a3dddeac3213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln']/div/div/select</value>
      <webElementGuid>d188aa13-f4a6-4cfa-abe1-3fcdc3037718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment Hauling'])[1]/following::select[1]</value>
      <webElementGuid>459ad59c-0e46-4b91-94ed-ab2695c70d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spare Parts, Fuel, And Lubricants'])[1]/preceding::select[1]</value>
      <webElementGuid>f7173cd0-f2d5-4fca-9075-3ac759e1246a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Waterborne Contractors', &quot;'&quot;, ' Equipment And Tools')])[1]/preceding::select[2]</value>
      <webElementGuid>daa9a7c1-1527-4af2-bdcd-c3936b4ad9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/div/select</value>
      <webElementGuid>a57636ec-4738-4cfc-ae67-93fa184dcd5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IM7InstallationFloaterPopup-IM7InstallationFloaterPanelSet-AdditionalCoveragesPanelSet-AdditionalCoveragesDV-0-CoverageInputSet-CovPatternInputGroup-IM7IFAddnlCovContrctFormIFAddnlCovEquipHln' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>0c552444-b5b3-45aa-9e8a-c5c2882ce7da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
