<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_AccountsReceivable_Supplemental_GenInfo_HistoryOfRecv_AccountReceivable</name>
   <tag></tag>
   <elementGuidId>69fbb2f0-005d-41ff-9c2e-6194864670b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd7a744a-d86a-48ba-ab67-46330e3d4a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3e35a57-9b36-4a6f-8da1-be0b72600e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation</value>
      <webElementGuid>f20d5f73-9c7b-4df1-ac02-794c3dd3086e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22642f77-05aa-423a-827c-0873feb53e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>36cf86b1-1473-4da3-8439-e03a1beb3b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e4332ccd-18e8-4aba-bfd3-2b6dacc17563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>e01f53ae-0514-41d5-8577-56a2fb6bdd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>b1d311e3-16e0-4e79-af56-383ae0da6ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>587d4d0c-a954-472e-b840-30f7707eb62e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation']</value>
      <webElementGuid>2e8641ae-3086-4b1a-b053-253e6109fcf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation']/div/input</value>
      <webElementGuid>f5dc9eaa-904c-4449-9033-9f5c6fe8de8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/div/input</value>
      <webElementGuid>45ef7535-29f7-4d8d-a5a6-4c98847806a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SubmissionWizard-SupplementalScreen-IM7Supplenetal-IM7GenericSupplementalPanelSet-AccountReceivablesGridDV-AccountReceivablesGrid-AccountReceivablesGridLV-0-Explanation']</value>
      <webElementGuid>e62edec0-c151-4109-8021-607e2da28381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
