<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_Transit_Checkbox_IM7251OwnersCargoCoverage</name>
   <tag></tag>
   <elementGuidId>0311c1f6-a464-4b74-a079-76d7f9eccf29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11b2add7-108d-451f-acf6-ffbb8a2e7cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>239f9956-29c6-4856-aa8a-685b655cd0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2ec659fa-77a3-44bb-841a-44f5525b5d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>IM 7251 Owner's Cargo Coverage visibility toggle</value>
      <webElementGuid>74fb973c-0520-41a1-acdd-0feef2c0a98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>2030f28f-bf6a-4106-b4f4-43f1e946d36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cb601d07-cc44-4087-90ae-609194f626ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>e7b0a05f-e67d-491c-96f6-4493e3f81b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>abd1012b-cb90-4e7d-a2e6-f644aa2bbeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>3f110967-f296-4513-949d-30f87778fc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'IM7TransitPopup-IM7TransitPanelSet-TransitCovCovPatterns-CoverageCategoryInputSet-1-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>7f018280-6c25-4a09-b0d3-6ea756de2e4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
