<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_IMC_MiscellaneousFloater_IM7505_BasicLoad</name>
   <tag></tag>
   <elementGuidId>403ddcf7-ee80-4e19-a245-6a4ea82cb024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9f91fba-af51-4fdb-841d-e457f77770a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b601738-bf3b-4ba2-8361-bf9a1ebb3796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell</value>
      <webElementGuid>4c9d842a-e6be-4311-b2b5-a36ba75802da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>937887a2-55aa-4cc0-a8ff-1a8663c5637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2f1bbc0d-31e5-48cc-b13a-91387608fb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>f2d10c28-d67a-460d-af92-67d51f55872b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>a72ca832-6e1e-4b33-9e96-804e3134be8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cb08e67b-464b-421d-a1dc-e6a5c7e5135d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell']</value>
      <webElementGuid>4daaa4a4-f9a9-4175-81ec-24d076cb1e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell']/div/input</value>
      <webElementGuid>e7d5cb58-1df4-495b-ad2f-f90bb2d130bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>0b7c33cd-61bb-4890-b63c-462f80795dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'IM7MiscellaneousFloaterPopup-IM7MiscellaneousFloaterPanelSet-MFCovCovPatterns-CoverageCategoryInputSet-5-CoverageInputSet-CovPatternInputGroup-BasicLoadCell']</value>
      <webElementGuid>58be456e-96e0-4f16-ac81-535e6ce4b409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
