<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_LineSelection_CheckBox_CommercialInlandMarine</name>
   <tag></tag>
   <elementGuidId>7dee32fc-8466-49f7-8e61-ec70d2af45d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a6d991b-8048-42a5-be7d-ee77249dd0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>627d71ac-cbec-4012-8c77-ae09b33e2b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ed02638-6e82-475d-b351-4b4d568c5578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected</value>
      <webElementGuid>99632438-18b4-4588-9c26-ce2c43fd5274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>87e49cd5-5748-4dec-8014-7ce36a2df462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>12652b96-f2ee-4850-bc28-ef259b9c953d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected']</value>
      <webElementGuid>340c9dcc-53e3-47ba-af55-8b3950048833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected']/div/input</value>
      <webElementGuid>43bdba60-07f1-497e-bd7c-f54c0e8aa3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/div/input</value>
      <webElementGuid>1dbe6b6d-f370-470c-9809-8a876eb3d81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPPLineSelectionScreen-CPPLineSelectionDV-2-LineSelected']</value>
      <webElementGuid>ba58fa73-bc0c-4ac0-be1c-1ece9b71b28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
