<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Locations_Link_Loc1</name>
   <tag></tag>
   <elementGuidId>f52505be-1e0e-434f-a1f6-585439bf8a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'0-Loc_button')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>684a5119-8311-4491-b187-ab38a5e7de03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c53f939-5b1a-4a40-90d6-4a234e3d459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-ActionValueWidget gw-focus</value>
      <webElementGuid>6f646faa-e136-4d1b-96b7-a65851f9e9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc_button</value>
      <webElementGuid>7b6c7cad-eff2-4437-bdbc-785948169d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc</value>
      <webElementGuid>d81b95d8-2026-49ca-be6b-f4fe5c25efee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b84c20bb-70b3-41c7-af54-86598f030931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1: 69 Washington Ave, Cicero, IN</value>
      <webElementGuid>93231054-c2f5-46fe-ad5c-a52ba7d77828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc_button&quot;)</value>
      <webElementGuid>343566ee-08a5-4339-8063-300ebd10de2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc_button']</value>
      <webElementGuid>9647641e-d707-4447-8b7a-70e7f89462b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc']/div/div</value>
      <webElementGuid>b0c1d2ae-56f3-42ab-90f3-12b1efe08c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::div[5]</value>
      <webElementGuid>f720085a-fe72-487f-9703-eee1b74294cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[3]/following::div[16]</value>
      <webElementGuid>44bfe69c-4cd6-4f34-ba5f-72629a1eba12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De'])[3]/preceding::div[18]</value>
      <webElementGuid>6f54aeab-97ba-4863-b9d1-64f291c0a19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::div[20]</value>
      <webElementGuid>2ce3cd26-a3dd-4764-939d-47a980419f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/div/div</value>
      <webElementGuid>e0dfb333-f182-4261-a9d5-4ad231e47815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-GL7WizardStepGroup-GL7LocationsScreen-GL7LocationsPanelSet-LocationsEdit_DP-LocationsEdit_LV-0-Loc_button' and (text() = '1: 69 Washington Ave, Cicero, IN' or . = '1: 69 Washington Ave, Cicero, IN')]</value>
      <webElementGuid>c5619528-c35a-461b-afbb-c1b84b518f1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
