<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Locations_Dropdown_PremOpCode</name>
   <tag></tag>
   <elementGuidId>ad4e2864-301f-4993-9caf-85d278536939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0bc0a963-ed98-4c8c-8953-e35854e3b363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input</value>
      <webElementGuid>dd2442b9-9173-4801-a410-b60d1fd2a6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2b0943bc-31ad-40a8-8ce0-773f33e7017f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5924da67-ede6-441f-ac09-3652b195832c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>506   </value>
      <webElementGuid>b4ed9564-b087-4c67-b231-d3913ec9d5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>1c50d03d-356e-4751-8029-8fb25ae7a3fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>619e5db2-185e-4d70-9af1-02a293c511e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input']/div/div/select</value>
      <webElementGuid>10813297-f74b-4561-aabe-4935b745e107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Premises/Operations Code'])[1]/following::select[1]</value>
      <webElementGuid>8c7ed623-e24d-4ffe-bcb6-932b5e74a0ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Territory'])[1]/following::select[1]</value>
      <webElementGuid>a3b1acdc-6474-4f9c-8250-f56b6b6bfaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products/Completed Operations Code'])[1]/preceding::select[1]</value>
      <webElementGuid>de05f998-a9a3-442a-8391-8312ed75d1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/select</value>
      <webElementGuid>2dcff164-a176-4b0b-882a-e83ad687f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'GL7LocationPopup-LocationScreen-GL7LocationDetailCV-SublinePropertiesPanel-0-LobEntityDV-16-LobInputSet-LobInternalInputSet-Input' and (text() = '   &lt;none>506   ' or . = '   &lt;none>506   ')]</value>
      <webElementGuid>5b3f7583-f903-40cf-8bcf-1bc95792c9e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
