<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_NewBuilding_Dropdown_BuildingImprovements</name>
   <tag></tag>
   <elementGuidId>8f5a48ee-6e61-4b39-94be-6f161665a7c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[text()='Building Improvements']/..//select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67c437e3-4667-4f80-a9de-2db82aa1f1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input</value>
      <webElementGuid>c2192af7-4494-46d0-a1fe-28f238a3a1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5f0696d-c5c6-4293-ae84-ff5c65e2a1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>9e96dd8c-8fd3-4c23-9521-275a34ed0827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>YesNo   </value>
      <webElementGuid>4dd9d095-ba8d-4aa6-af32-7840f0470bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>d4329d44-26b8-4964-b19a-d34203715cc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input']</value>
      <webElementGuid>8039c6e3-d143-4cf9-b578-0c1bb9e39b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input']/div/div/select</value>
      <webElementGuid>06d12b55-339a-4a12-9446-c8d978814141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Building Improvements'])[1]/following::select[1]</value>
      <webElementGuid>a963f859-8132-4ae6-bb58-08d026e32a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Improvements'])[1]/following::select[1]</value>
      <webElementGuid>e829c5fb-f6c4-479c-aa96-49282ac41e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other Occupancies'])[1]/preceding::select[1]</value>
      <webElementGuid>1f923fb0-c961-4969-ac1a-385c84ab3f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Basements'])[1]/preceding::select[1]</value>
      <webElementGuid>b0187d2e-86f2-433c-a682-985298cb438e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div[2]/div/div/div/select</value>
      <webElementGuid>eb8d1223-b19d-4568-b1ae-e5f9461c1e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CP7BuildingPopup-CP7BuildingCV-LobEntityDV-33-LobInputSet-LobInternalInputSet-Input' and (text() = '   &lt;none>YesNo   ' or . = '   &lt;none>YesNo   ')]</value>
      <webElementGuid>17b8ea43-03c9-4ca2-99b0-98b494d871e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
