<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_NewSubmissions_Button_LOB_Select_WC</name>
   <tag></tag>
   <elementGuidId>6c9a83fb-37bc-4bef-9dd5-ad74bd63ea73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'Name')]//div[contains(text(),'Workers')]/../../../../..//div[text()='Select']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb29552a-27b1-4144-a998-82a4e7cbd496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      <webElementGuid>335cedec-f5ed-47fd-b660-c112ca57f259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>5a0937d3-8459-4886-b3dd-494b5c460b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>c3f5c841-bd77-45ef-a37c-c1b778c6ad57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>81d12d86-dcfa-4741-b0de-c3a68378a26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>17932fcb-1f59-428f-97ea-e7b2f0e8549d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>8f31c114-de38-4fd4-be33-220dcbd59ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission&quot;)</value>
      <webElementGuid>724ac5ee-1d7a-415d-8a25-9be4065c11fa</webElementGuid>
   </webElementProperties>
</WebElementEntity>
