<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_NewBuilding_SearchIcon_CPClassCodeSearch</name>
   <tag></tag>
   <elementGuidId>2262ef50-0e4a-40c1-90b5-d7fece431185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-CP7BuildingParentLocationPickDV-Classcode-SelectClasscode']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CP7BuildingPopup-CP7BuildingCV-CP7BuildingParentLocationPickDV-Classcode-SelectClasscode > span.gw-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>023673de-0302-4bd5-bb9c-d5f852942901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-icon</value>
      <webElementGuid>c4ec9257-1e82-46c3-9712-8dd129d6ab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99b931e9-9b65-45b9-8fb2-4d375eb32237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>gw-search-icon</value>
      <webElementGuid>0b687d51-39e2-41c8-b701-2b6b48562be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CP7BuildingPopup-CP7BuildingCV-CP7BuildingParentLocationPickDV-Classcode-SelectClasscode&quot;)/span[@class=&quot;gw-icon&quot;]</value>
      <webElementGuid>7a5d52d2-963e-4dd1-93cc-ef28103ab60a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CP7BuildingPopup-CP7BuildingCV-CP7BuildingParentLocationPickDV-Classcode-SelectClasscode']/span</value>
      <webElementGuid>12ec2421-2554-4c80-9336-0d55f487ae14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/span</value>
      <webElementGuid>62a8a901-8a3e-44e3-b144-2ee98817229f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
