<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_RiskAnalysis_Button_SpecialApprove</name>
   <tag></tag>
   <elementGuidId>81140fea-fa6b-4238-aa4c-26fdd885b9aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id,'UWIssueRowSet-SpecialApprove')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-RiskEvaluationPanelSet-3-UWIssueRowSet-SpecialApprove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8976972e-eb59-40ee-94ae-9dc5aade2985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-RiskEvaluationPanelSet-3-UWIssueRowSet-SpecialApprove</value>
      <webElementGuid>6f859d37-0dc2-4a2c-b033-1ad3eb4c9f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-big-button gw-actionable gw-focus</value>
      <webElementGuid>f9a20c9c-fe20-4dec-83af-d8941b64d980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>4669a6a5-4921-4dd6-9456-5c0d55525789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-confirm</name>
      <type>Main</type>
      <value>Your authority profile does not allow you to approve this issue. If you believe that you have or require this authority, please notify the system administrator. You also have a special override permission to approve it anyway. Would you like to use this override permission to give approval?</value>
      <webElementGuid>59e89156-9041-46e9-9812-d2c343896254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>a7ba6d90-73ab-42c1-af25-4c88a0349ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5bf686e-03f1-402e-92da-1f57e518d28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Special Approve</value>
      <webElementGuid>8a40e606-39e5-4a1b-b347-110f3fda2cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-Job_RiskAnalysisScreen-RiskAnalysisCV-RiskEvaluationPanelSet-3-UWIssueRowSet-SpecialApprove&quot;)</value>
      <webElementGuid>820a22cf-1ef7-4c38-8013-f0ebcc63de2b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
