<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Risks_Button_AddBuilding</name>
   <tag></tag>
   <elementGuidId>ae724f7a-a4d9-4d39-8d43-74e2955fe0ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'ABAdd Building' or . = 'Add Building')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>daa9724e-f940-4a52-9a9d-af2b1f28f6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3aa69a44-4a19-4a28-b014-51ffe96bfc1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-hasDivider gw-focus</value>
      <webElementGuid>eb59cc11-aa7f-4c91-b7cc-cb8327e62b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9b67ebd-6c86-4a93-a80d-ce1eec627fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c616d671-3e1a-4f2a-a252-7cb48d0a665f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:^</value>
      <webElementGuid>6f60e78d-6a87-4d99-97ff-0ef992c24931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0585289-488b-4bc5-96fc-9b41492c967d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABAdd Building</value>
      <webElementGuid>02e711ef-dff7-44ee-a804-802008001c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CP7WizardStepGroup-CP7RisksScreen-CP7RisksPanelSet-CP7RiskDetailsPanelSet-AddBuildingButton&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]</value>
      <webElementGuid>19217c25-0a05-4e0c-9991-0975c947e090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CP7WizardStepGroup-CP7RisksScreen-CP7RisksPanelSet-CP7RiskDetailsPanelSet-AddBuildingButton']/div</value>
      <webElementGuid>1eaf0602-1423-4036-b8b6-5331de2f5d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Construction'])[3]/following::div[57]</value>
      <webElementGuid>07823026-6a77-42b5-827a-42da76bd1e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/table/tbody/tr/td/div/div/div/div/div</value>
      <webElementGuid>7643d0c8-140b-4060-9cb1-956c32dac2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ABAdd Building' or . = 'ABAdd Building')]</value>
      <webElementGuid>14a92843-57ad-4ccf-853f-5c44264094f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
