<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_StartCancellation_Dropdown_Source</name>
   <tag></tag>
   <elementGuidId>0f1afc99-bd04-485a-be76-1d2b3c863d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name='StartCancellation-StartCancellationScreen-CancelPolicyDV-Source']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
