<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Supplemental_WaterWellDrillingContrctrsSupplQues_TextBox_WhatIsTheAvgNumOfYrsExp_DrillersAndPumpInstallers</name>
   <tag></tag>
   <elementGuidId>8589c7e6-cac6-4435-9482-d888803d0d43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Drillers &amp; pump installers')]/../../../../..//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64e22605-4400-48e8-9632-81747c7e2e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09a87a0e-7759-41be-9ccd-ce3daddb3374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost</value>
      <webElementGuid>538d756c-5d65-4bfb-babc-74dc7ff02e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9f2d545d-9aaf-46df-9147-9707c257b1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b5f89f30-a664-40b8-9b3d-0d10ac759ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>71df8a4c-f51e-4240-bbf7-3ca06bef55a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>210bd857-9350-43b4-97b6-355cc640fd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>0174984b-79a0-4d59-bd8c-e656648c7078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost']</value>
      <webElementGuid>cd376bbe-14ab-4920-a603-50ada52a5b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost']/div/input</value>
      <webElementGuid>fc2484b5-fbf4-472a-a3e1-53864084143a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td[2]/div/div/div/input</value>
      <webElementGuid>a48253e4-3b78-4c57-8fb5-28afa33934a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-22-QuestionModalInput-IntegerFieldInput_NoPost']</value>
      <webElementGuid>d7f2ea2a-9578-4370-95d7-697958841440</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
