<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Supplemental_WaterWellDrillingContrctrsSupplQues_TextBox_OnceYouhitWaterHowDoYouDetermine</name>
   <tag></tag>
   <elementGuidId>0337a05b-ab95-4465-9f8d-47a4e54e0ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'Once you hit water, how do you determine')]/../../../../..//textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e462744f-e1b1-421e-b49d-e99b16760b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7736c452-adf5-41b0-9cb6-51d84f30c6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost</value>
      <webElementGuid>cb53c275-c2e0-4916-9fd6-a146a27b2eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1333</value>
      <webElementGuid>6dcf980e-38e5-403c-a464-38986035bbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>cdc61da0-2054-418b-aab1-22e282037bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost&quot;)/div[@class=&quot;gw-vw--value&quot;]/textarea[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>db000eac-7969-458c-8007-c98d005d7add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost']</value>
      <webElementGuid>220a022a-4aa8-4c04-9f70-372837385900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost']/div/textarea</value>
      <webElementGuid>b68df310-b577-4f1a-8908-3e56eac16203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/div/div/div/textarea</value>
      <webElementGuid>2ff2d021-436e-40d6-8af7-13325ee51c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-18-QuestionModalInput-StringTextAreaInput_NoPost']</value>
      <webElementGuid>5a42330f-9bbb-4934-a9e3-62ae5ed312df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
