<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Supplemental_CheckBox_SafetyManual</name>
   <tag></tag>
   <elementGuidId>a0468fab-7a60-4725-a438-cac3306303e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1654dc96-7f18-41d5-b489-3c7f8cd5b01c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f10ce9d-cdb1-45b0-87c6-23134e90ccd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>680bf8e7-d18f-4024-b9d9-237353cec114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost</value>
      <webElementGuid>f94a1f96-c95b-45b2-a114-ef8fdbfb5e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>ad9a8b0d-64d2-4638-8cb0-d2980631eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>a4b8abb1-4fa8-49af-b317-ec81b58d5339</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost']</value>
      <webElementGuid>52fa5ae6-796b-4099-bb87-9fdb814ded84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost']/div/input</value>
      <webElementGuid>d18919d8-25e1-4f20-8e17-974d580db7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/input</value>
      <webElementGuid>05529f28-2bdb-4a3c-8870-3585df9a1008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'SubmissionWizard-SupplementalScreen-GeneralQuestion-QuestionSetLV-1-QuestionModalInput-BooleanCheckboxInput_NoPost']</value>
      <webElementGuid>6441a637-3f5c-42b6-97b5-27e17b0d7d25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
