<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_Supplemental_WaterWellDrillingContrctrsSupplQues_TextBox_WhatTypeOfWorkDoYouSubcontract</name>
   <tag></tag>
   <elementGuidId>18783b21-f5ae-467d-92ca-bd6737bfa31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'What type of work do you subcontract')]/../../../../..//input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9ba46e9-1ecd-40c2-9b66-fd2ba8fb7702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>743e9a69-9233-4a53-8a91-5ced658d7d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost</value>
      <webElementGuid>3879875c-e3c3-459f-b4fc-1ec64ab94487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e782147e-b752-49bc-97b5-ecc9a6782630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1333</value>
      <webElementGuid>a529f90d-f22c-4d91-8c2c-bfd58c56dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>19e30c52-c807-402b-b251-8dda5c312607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>49d2b522-b49a-406b-8a3c-944be259f742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>81816360-211d-4600-b3e7-3bc9da52ffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>25f408e6-a109-438d-b0c3-455eef6ce63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost']</value>
      <webElementGuid>ee3ac3a6-c4d8-4bad-bc1a-4137de8d8268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost']/div/input</value>
      <webElementGuid>0942181f-0ad6-4d31-9a3d-6ac8de8520bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/div/div/div/input</value>
      <webElementGuid>da2a2a83-6dfa-40ad-8d2e-c3e9b222bacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SubmissionWizard-SupplementalScreen-GL7Supplenetal-GL7GenericSupplementalPanelSet-waterWellSupplemetal-QuestionSetLV-13-QuestionModalInput-StringFieldInput_NoPost']</value>
      <webElementGuid>4e9e1d55-01a7-44ec-a177-0b77cc0dca1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
