<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_WC_Supplemental_Radio_No_AnyGroupTransportationProvided</name>
   <tag></tag>
   <elementGuidId>3fa68c4d-1f14-4192-916c-34134e09fb0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83a8c50f-96a4-4ce0-9c72-4f039ffb1c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1</value>
      <webElementGuid>a214109d-ffc8-41a3-9916-de5306b354cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>00c8b889-e3c3-4ae0-b894-68d80125cc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost</value>
      <webElementGuid>f93c1e3a-daa4-43ef-b7ca-ff168b317cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d244c5a5-b851-4ec3-97a7-e922be528858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-RangeRadioValueWidget--input gw-focus</value>
      <webElementGuid>54e72f8e-2901-4c3b-b15e-f8bc25f7fce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbfd788f-4317-4d78-95c4-e0986225513b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>5fbc399f-4c7d-4acc-8d08-add9f1ad6b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1&quot;)</value>
      <webElementGuid>5d7ac79e-fc78-4ebd-9f86-19a1bef9c273</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1']</value>
      <webElementGuid>374baebe-66cf-4cbc-bd02-9aa91390751b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost']/div/div/label[2]/span/input</value>
      <webElementGuid>3361009f-09bb-40a7-9854-22de328ebf8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/div/div/div/div/label[2]/span/input</value>
      <webElementGuid>9f276e2a-41a7-4546-b2fd-e94c1c5abb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost_1' and @type = 'radio' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-8-QuestionModalInput-BooleanRadioInput_NoPost']</value>
      <webElementGuid>6aca8c7f-d262-423c-8f3e-2e1f35a5ca7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
