<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_WC_Supplemental_Radio_No_AreAthleticTeamsSponsored</name>
   <tag></tag>
   <elementGuidId>c90d6fd3-a24a-4e1b-bc28-ffee6a6e240b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e1869de-cb2d-4505-b54d-f76799bd1216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1</value>
      <webElementGuid>3ee8ef7a-b134-4a56-b0fe-cc1b608c9a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d0921271-2321-40b7-b376-f488ca3531ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost</value>
      <webElementGuid>4a2f440e-9cbc-4376-8bd2-4de3d94e3e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d5cd3f4-f178-45e9-aa4f-d3e1f445cb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-RangeRadioValueWidget--input gw-focus</value>
      <webElementGuid>a439a489-e9f4-4a78-962e-3182b5f122c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b52750d1-6475-43cd-944a-8386805cd80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>0c0d1676-5c27-4836-894e-5a3141916edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1&quot;)</value>
      <webElementGuid>2167a164-f455-4af5-8e82-1ecca381e92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1']</value>
      <webElementGuid>060cb69c-277e-4b11-8f8a-9b4e7e44c2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost']/div/div/label[2]/span/input</value>
      <webElementGuid>df118f9a-d1f3-40f6-a242-d796cb1063df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]/div/div/div/div/label[2]/span/input</value>
      <webElementGuid>fcc8b566-e2d9-4839-bc1c-4b9b6185e856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost_1' and @type = 'radio' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-14-QuestionModalInput-BooleanRadioInput_NoPost']</value>
      <webElementGuid>1b8ed0e7-0ed6-4f12-8203-5d534e183d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
