<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PC_WC_Supplemental_Radio_No_DoAnyEmployeesPredominantlyWorkAtHome</name>
   <tag></tag>
   <elementGuidId>51ab7588-0e34-46af-8b24-a935ccc76356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>218e8070-a560-4ff4-b928-a781dfcb9fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1</value>
      <webElementGuid>1130986d-df82-4b15-963f-93f713a84289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ad3de1c0-a97f-4ef0-924d-0c6f8cadfa26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput</value>
      <webElementGuid>189be672-9e74-47e1-bd13-ad16d65be946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6c40166-3aae-457e-b1c5-b1b9fba8e6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-RangeRadioValueWidget--input gw-focus</value>
      <webElementGuid>806cadd4-0689-4f19-a14b-5c078164ae07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b94c24bb-e432-4916-9057-2d0aa4af2976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>f7126715-6132-4fab-8c13-ece09a3bd868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1&quot;)</value>
      <webElementGuid>46bc04f7-bb8e-48ea-95d5-4896aa00fa1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1']</value>
      <webElementGuid>54a45497-5fdf-4012-b636-43e2a9aa92b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput']/div/div/label[2]/span/input</value>
      <webElementGuid>89284b64-a2ff-485a-90fd-a77f494de518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[2]/div/div/div/div/label[2]/span/input</value>
      <webElementGuid>4f0a4934-16d1-4eb6-9fa7-21ffa63cf9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput_1' and @type = 'radio' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-WC7SupplementalScreen-QuestionSetsDV-0-QuestionSetLV-21-QuestionModalInput-BooleanRadioInput']</value>
      <webElementGuid>816498db-6531-4d7d-81d0-5fdb86d05672</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
